<option value="" disabled selected>Selecciona tu ciudad</option>
    <option value='ANTIOQUIA-MEDELLIN'>ANTIOQUIA-MEDELLIN</option>
    <option value='ANTIOQUIA-ABEJORRAL'>ANTIOQUIA-ABEJORRAL</option>
    <option value='ANTIOQUIA-ABRIAQUI'>ANTIOQUIA-ABRIAQUI</option>
    <option value='ANTIOQUIA-ALEJANDRIA'>ANTIOQUIA-ALEJANDRIA</option>
    <option value='ANTIOQUIA-AMAGA'>ANTIOQUIA-AMAGA</option>
    <option value='ANTIOQUIA-AMALFI'>ANTIOQUIA-AMALFI</option>
    <option value='ANTIOQUIA-ANDES'>ANTIOQUIA-ANDES</option>
    <option value='ANTIOQUIA-ANGELOPOLIS'>ANTIOQUIA-ANGELOPOLIS</option>
    <option value='ANTIOQUIA-ANGOSTURA'>ANTIOQUIA-ANGOSTURA</option>
    <option value='ANTIOQUIA-ANORI'>ANTIOQUIA-ANORI</option>
    <option value='ANTIOQUIA-SANTAFE DE ANTIOQUIA'>ANTIOQUIA-SANTAFE DE ANTIOQUIA</option>
    <option value='ANTIOQUIA-ANZA'>ANTIOQUIA-ANZA</option>
    <option value='ANTIOQUIA-APARTADO'>ANTIOQUIA-APARTADO</option>
    <option value='ANTIOQUIA-ARBOLETES'>ANTIOQUIA-ARBOLETES</option>
    <option value='ANTIOQUIA-ARGELIA'>ANTIOQUIA-ARGELIA</option>
    <option value='ANTIOQUIA-ARMENIA'>ANTIOQUIA-ARMENIA</option>
    <option value='ANTIOQUIA-BARBOSA'>ANTIOQUIA-BARBOSA</option>
    <option value='ANTIOQUIA-BELMIRA'>ANTIOQUIA-BELMIRA</option>
    <option value='ANTIOQUIA-BELLO'>ANTIOQUIA-BELLO</option>
    <option value='ANTIOQUIA-BETANIA'>ANTIOQUIA-BETANIA</option>
    <option value='ANTIOQUIA-BETULIA'>ANTIOQUIA-BETULIA</option>
    <option value='ANTIOQUIA-CIUDAD BOLIVAR'>ANTIOQUIA-CIUDAD BOLIVAR</option>
    <option value='ANTIOQUIA-BRICEÑO'>ANTIOQUIA-BRICEÑO</option>
    <option value='ANTIOQUIA-BURITICA'>ANTIOQUIA-BURITICA</option>
    <option value='ANTIOQUIA-CACERES'>ANTIOQUIA-CACERES</option>
    <option value='ANTIOQUIA-CAICEDO'>ANTIOQUIA-CAICEDO</option>
    <option value='ANTIOQUIA-CALDAS'>ANTIOQUIA-CALDAS</option>
    <option value='ANTIOQUIA-CAMPAMENTO'>ANTIOQUIA-CAMPAMENTO</option>
    <option value='ANTIOQUIA-CAÑASGORDAS'>ANTIOQUIA-CAÑASGORDAS</option>
    <option value='ANTIOQUIA-CARACOLI'>ANTIOQUIA-CARACOLI</option>
    <option value='ANTIOQUIA-CARAMANTA'>ANTIOQUIA-CARAMANTA</option>
    <option value='ANTIOQUIA-CAREPA'>ANTIOQUIA-CAREPA</option>
    <option value='ANTIOQUIA-EL CARMEN DE VIBORAL'>ANTIOQUIA-EL CARMEN DE VIBORAL</option>
    <option value='ANTIOQUIA-CAROLINA'>ANTIOQUIA-CAROLINA</option>
    <option value='ANTIOQUIA-CAUCASIA'>ANTIOQUIA-CAUCASIA</option>
    <option value='ANTIOQUIA-CHIGORODO'>ANTIOQUIA-CHIGORODO</option>
    <option value='ANTIOQUIA-CISNEROS'>ANTIOQUIA-CISNEROS</option>
    <option value='ANTIOQUIA-COCORNA'>ANTIOQUIA-COCORNA</option>
    <option value='ANTIOQUIA-CONCEPCION'>ANTIOQUIA-CONCEPCION</option>
    <option value='ANTIOQUIA-CONCORDIA'>ANTIOQUIA-CONCORDIA</option>
    <option value='ANTIOQUIA-COPACABANA'>ANTIOQUIA-COPACABANA</option>
    <option value='ANTIOQUIA-DABEIBA'>ANTIOQUIA-DABEIBA</option>
    <option value='ANTIOQUIA-DON MATIAS'>ANTIOQUIA-DON MATIAS</option>
    <option value='ANTIOQUIA-EBEJICO'>ANTIOQUIA-EBEJICO</option>
    <option value='ANTIOQUIA-EL BAGRE'>ANTIOQUIA-EL BAGRE</option>
    <option value='ANTIOQUIA-ENTRERRIOS'>ANTIOQUIA-ENTRERRIOS</option>
    <option value='ANTIOQUIA-ENVIGADO'>ANTIOQUIA-ENVIGADO</option>
    <option value='ANTIOQUIA-FREDONIA'>ANTIOQUIA-FREDONIA</option>
    <option value='ANTIOQUIA-FRONTINO'>ANTIOQUIA-FRONTINO</option>
    <option value='ANTIOQUIA-GIRALDO'>ANTIOQUIA-GIRALDO</option>
    <option value='ANTIOQUIA-GIRARDOTA'>ANTIOQUIA-GIRARDOTA</option>
    <option value='ANTIOQUIA-GOMEZ PLATA'>ANTIOQUIA-GOMEZ PLATA</option>
    <option value='ANTIOQUIA-GRANADA'>ANTIOQUIA-GRANADA</option>
    <option value='ANTIOQUIA-GUADALUPE'>ANTIOQUIA-GUADALUPE</option>
    <option value='ANTIOQUIA-GUARNE'>ANTIOQUIA-GUARNE</option>
    <option value='ANTIOQUIA-GUATAPE'>ANTIOQUIA-GUATAPE</option>
    <option value='ANTIOQUIA-HELICONIA'>ANTIOQUIA-HELICONIA</option>
    <option value='ANTIOQUIA-HISPANIA'>ANTIOQUIA-HISPANIA</option>
    <option value='ANTIOQUIA-ITAGUI'>ANTIOQUIA-ITAGUI</option>
    <option value='ANTIOQUIA-ITUANGO'>ANTIOQUIA-ITUANGO</option>
    <option value='ANTIOQUIA-JARDIN'>ANTIOQUIA-JARDIN</option>
    <option value='ANTIOQUIA-JERICO'>ANTIOQUIA-JERICO</option>
    <option value='ANTIOQUIA-LA CEJA'>ANTIOQUIA-LA CEJA</option>
    <option value='ANTIOQUIA-LA ESTRELLA'>ANTIOQUIA-LA ESTRELLA</option>
    <option value='ANTIOQUIA-LA PINTADA'>ANTIOQUIA-LA PINTADA</option>
    <option value='ANTIOQUIA-LA UNION'>ANTIOQUIA-LA UNION</option>
    <option value='ANTIOQUIA-LIBORINA'>ANTIOQUIA-LIBORINA</option>
    <option value='ANTIOQUIA-MACEO'>ANTIOQUIA-MACEO</option>
    <option value='ANTIOQUIA-MARINILLA'>ANTIOQUIA-MARINILLA</option>
    <option value='ANTIOQUIA-MONTEBELLO'>ANTIOQUIA-MONTEBELLO</option>
    <option value='ANTIOQUIA-MURINDO'>ANTIOQUIA-MURINDO</option>
    <option value='ANTIOQUIA-MUTATA'>ANTIOQUIA-MUTATA</option>
    <option value='ANTIOQUIA-NARIÑO'>ANTIOQUIA-NARIÑO</option>
    <option value='ANTIOQUIA-NECOCLI'>ANTIOQUIA-NECOCLI</option>
    <option value='ANTIOQUIA-NECHI'>ANTIOQUIA-NECHI</option>
    <option value='ANTIOQUIA-OLAYA'>ANTIOQUIA-OLAYA</option>
    <option value='ANTIOQUIA-PEÐOL'>ANTIOQUIA-PEÐOL</option>
    <option value='ANTIOQUIA-PEQUE'>ANTIOQUIA-PEQUE</option>
    <option value='ANTIOQUIA-PUEBLORRICO'>ANTIOQUIA-PUEBLORRICO</option>
    <option value='ANTIOQUIA-PUERTO BERRIO'>ANTIOQUIA-PUERTO BERRIO</option>
    <option value='ANTIOQUIA-PUERTO NARE'>ANTIOQUIA-PUERTO NARE</option>
    <option value='ANTIOQUIA-PUERTO TRIUNFO'>ANTIOQUIA-PUERTO TRIUNFO</option>
    <option value='ANTIOQUIA-REMEDIOS'>ANTIOQUIA-REMEDIOS</option>
    <option value='ANTIOQUIA-RETIRO'>ANTIOQUIA-RETIRO</option>
    <option value='ANTIOQUIA-RIONEGRO'>ANTIOQUIA-RIONEGRO</option>
    <option value='ANTIOQUIA-SABANALARGA'>ANTIOQUIA-SABANALARGA</option>
    <option value='ANTIOQUIA-SABANETA'>ANTIOQUIA-SABANETA</option>
    <option value='ANTIOQUIA-SALGAR'>ANTIOQUIA-SALGAR</option>
    <option value='ANTIOQUIA-SAN ANDRES DE CUERQUIA'>ANTIOQUIA-SAN ANDRES DE CUERQUIA</option>
    <option value='ANTIOQUIA-SAN CARLOS'>ANTIOQUIA-SAN CARLOS</option>
    <option value='ANTIOQUIA-SAN FRANCISCO'>ANTIOQUIA-SAN FRANCISCO</option>
    <option value='ANTIOQUIA-SAN JERONIMO'>ANTIOQUIA-SAN JERONIMO</option>
    <option value='ANTIOQUIA-SAN JOSE DE LA MONTAÑA'>ANTIOQUIA-SAN JOSE DE LA MONTAÑA</option>
    <option value='ANTIOQUIA-SAN JUAN DE URABA'>ANTIOQUIA-SAN JUAN DE URABA</option>
    <option value='ANTIOQUIA-SAN LUIS'>ANTIOQUIA-SAN LUIS</option>
    <option value='ANTIOQUIA-SAN PEDRO'>ANTIOQUIA-SAN PEDRO</option>
    <option value='ANTIOQUIA-SAN PEDRO DE URABA'>ANTIOQUIA-SAN PEDRO DE URABA</option>
    <option value='ANTIOQUIA-SAN RAFAEL'>ANTIOQUIA-SAN RAFAEL</option>
    <option value='ANTIOQUIA-SAN ROQUE'>ANTIOQUIA-SAN ROQUE</option>
    <option value='ANTIOQUIA-SAN VICENTE'>ANTIOQUIA-SAN VICENTE</option>
    <option value='ANTIOQUIA-SANTA BARBARA'>ANTIOQUIA-SANTA BARBARA</option>
    <option value='ANTIOQUIA-SANTA ROSA DE OSOS'>ANTIOQUIA-SANTA ROSA DE OSOS</option>
    <option value='ANTIOQUIA-SANTO DOMINGO'>ANTIOQUIA-SANTO DOMINGO</option>
    <option value='ANTIOQUIA-EL SANTUARIO'>ANTIOQUIA-EL SANTUARIO</option>
    <option value='ANTIOQUIA-SEGOVIA'>ANTIOQUIA-SEGOVIA</option>
    <option value='ANTIOQUIA-SONSON'>ANTIOQUIA-SONSON</option>
    <option value='ANTIOQUIA-SOPETRAN'>ANTIOQUIA-SOPETRAN</option>
    <option value='ANTIOQUIA-TAMESIS'>ANTIOQUIA-TAMESIS</option>
    <option value='ANTIOQUIA-TARAZA'>ANTIOQUIA-TARAZA</option>
    <option value='ANTIOQUIA-TARSO'>ANTIOQUIA-TARSO</option>
    <option value='ANTIOQUIA-TITIRIBI'>ANTIOQUIA-TITIRIBI</option>
    <option value='ANTIOQUIA-TOLEDO'>ANTIOQUIA-TOLEDO</option>
    <option value='ANTIOQUIA-TURBO'>ANTIOQUIA-TURBO</option>
    <option value='ANTIOQUIA-URAMITA'>ANTIOQUIA-URAMITA</option>
    <option value='ANTIOQUIA-URRAO'>ANTIOQUIA-URRAO</option>
    <option value='ANTIOQUIA-VALDIVIA'>ANTIOQUIA-VALDIVIA</option>
    <option value='ANTIOQUIA-VALPARAISO'>ANTIOQUIA-VALPARAISO</option>
    <option value='ANTIOQUIA-VEGACHI'>ANTIOQUIA-VEGACHI</option>
    <option value='ANTIOQUIA-VENECIA'>ANTIOQUIA-VENECIA</option>
    <option value='ANTIOQUIA-VIGIA DEL FUERTE'>ANTIOQUIA-VIGIA DEL FUERTE</option>
    <option value='ANTIOQUIA-YALI'>ANTIOQUIA-YALI</option>
    <option value='ANTIOQUIA-YARUMAL'>ANTIOQUIA-YARUMAL</option>
    <option value='ANTIOQUIA-YOLOMBO'>ANTIOQUIA-YOLOMBO</option>
    <option value='ANTIOQUIA-YONDO'>ANTIOQUIA-YONDO</option>
    <option value='ANTIOQUIA-ZARAGOZA'>ANTIOQUIA-ZARAGOZA</option>
    <option value='ATLANTICO-BARRANQUILLA'>ATLANTICO-BARRANQUILLA</option>
    <option value='ATLANTICO-BARANOA'>ATLANTICO-BARANOA</option>
    <option value='ATLANTICO-CAMPO DE LA CRUZ'>ATLANTICO-CAMPO DE LA CRUZ</option>
    <option value='ATLANTICO-CANDELARIA'>ATLANTICO-CANDELARIA</option>
    <option value='ATLANTICO-GALAPA'>ATLANTICO-GALAPA</option>
    <option value='ATLANTICO-JUAN DE ACOSTA'>ATLANTICO-JUAN DE ACOSTA</option>
    <option value='ATLANTICO-LURUACO'>ATLANTICO-LURUACO</option>
    <option value='ATLANTICO-MALAMBO'>ATLANTICO-MALAMBO</option>
    <option value='ATLANTICO-MANATI'>ATLANTICO-MANATI</option>
    <option value='ATLANTICO-PALMAR DE VARELA'>ATLANTICO-PALMAR DE VARELA</option>
    <option value='ATLANTICO-PIOJO'>ATLANTICO-PIOJO</option>
    <option value='ATLANTICO-POLONUEVO'>ATLANTICO-POLONUEVO</option>
    <option value='ATLANTICO-PONEDERA'>ATLANTICO-PONEDERA</option>
    <option value='ATLANTICO-PUERTO COLOMBIA'>ATLANTICO-PUERTO COLOMBIA</option>
    <option value='ATLANTICO-REPELON'>ATLANTICO-REPELON</option>
    <option value='ATLANTICO-SABANAGRANDE'>ATLANTICO-SABANAGRANDE</option>
    <option value='ATLANTICO-SABANALARGA'>ATLANTICO-SABANALARGA</option>
    <option value='ATLANTICO-SANTA LUCIA'>ATLANTICO-SANTA LUCIA</option>
    <option value='ATLANTICO-SANTO TOMAS'>ATLANTICO-SANTO TOMAS</option>
    <option value='ATLANTICO-SOLEDAD'>ATLANTICO-SOLEDAD</option>
    <option value='ATLANTICO-SUAN'>ATLANTICO-SUAN</option>
    <option value='ATLANTICO-TUBARA'>ATLANTICO-TUBARA</option>
    <option value='ATLANTICO-USIACURI'>ATLANTICO-USIACURI</option>
    <option value='BOGOTA-BOGOTA, D.C.'>BOGOTA-BOGOTA, D.C.</option>
    <option value='BOLIVAR-CARTAGENA'>BOLIVAR-CARTAGENA</option>
    <option value='BOLIVAR-ACHI'>BOLIVAR-ACHI</option>
    <option value='BOLIVAR-ALTOS DEL ROSARIO'>BOLIVAR-ALTOS DEL ROSARIO</option>
    <option value='BOLIVAR-ARENAL'>BOLIVAR-ARENAL</option>
    <option value='BOLIVAR-ARJONA'>BOLIVAR-ARJONA</option>
    <option value='BOLIVAR-ARROYOHONDO'>BOLIVAR-ARROYOHONDO</option>
    <option value='BOLIVAR-BARRANCO DE LOBA'>BOLIVAR-BARRANCO DE LOBA</option>
    <option value='BOLIVAR-CALAMAR'>BOLIVAR-CALAMAR</option>
    <option value='BOLIVAR-CANTAGALLO'>BOLIVAR-CANTAGALLO</option>
    <option value='BOLIVAR-CICUCO'>BOLIVAR-CICUCO</option>
    <option value='BOLIVAR-CORDOBA'>BOLIVAR-CORDOBA</option>
    <option value='BOLIVAR-CLEMENCIA'>BOLIVAR-CLEMENCIA</option>
    <option value='BOLIVAR-EL CARMEN DE BOLIVAR'>BOLIVAR-EL CARMEN DE BOLIVAR</option>
    <option value='BOLIVAR-EL GUAMO'>BOLIVAR-EL GUAMO</option>
    <option value='BOLIVAR-EL PEÑON'>BOLIVAR-EL PEÑON</option>
    <option value='BOLIVAR-HATILLO DE LOBA'>BOLIVAR-HATILLO DE LOBA</option>
    <option value='BOLIVAR-MAGANGUE'>BOLIVAR-MAGANGUE</option>
    <option value='BOLIVAR-MAHATES'>BOLIVAR-MAHATES</option>
    <option value='BOLIVAR-MARGARITA'>BOLIVAR-MARGARITA</option>
    <option value='BOLIVAR-MARIA LA BAJA'>BOLIVAR-MARIA LA BAJA</option>
    <option value='BOLIVAR-MONTECRISTO'>BOLIVAR-MONTECRISTO</option>
    <option value='BOLIVAR-MOMPOS'>BOLIVAR-MOMPOS</option>
    <option value='BOLIVAR-NOROSI'>BOLIVAR-NOROSI</option>
    <option value='BOLIVAR-MORALES'>BOLIVAR-MORALES</option>
    <option value='BOLIVAR-PINILLOS'>BOLIVAR-PINILLOS</option>
    <option value='BOLIVAR-REGIDOR'>BOLIVAR-REGIDOR</option>
    <option value='BOLIVAR-RIO VIEJO'>BOLIVAR-RIO VIEJO</option>
    <option value='BOLIVAR-SAN CRISTOBAL'>BOLIVAR-SAN CRISTOBAL</option>
    <option value='BOLIVAR-SAN ESTANISLAO'>BOLIVAR-SAN ESTANISLAO</option>
    <option value='BOLIVAR-SAN FERNANDO'>BOLIVAR-SAN FERNANDO</option>
    <option value='BOLIVAR-SAN JACINTO'>BOLIVAR-SAN JACINTO</option>
    <option value='BOLIVAR-SAN JACINTO DEL CAUCA'>BOLIVAR-SAN JACINTO DEL CAUCA</option>
    <option value='BOLIVAR-SAN JUAN NEPOMUCENO'>BOLIVAR-SAN JUAN NEPOMUCENO</option>
    <option value='BOLIVAR-SAN MARTIN DE LOBA'>BOLIVAR-SAN MARTIN DE LOBA</option>
    <option value='BOLIVAR-SAN PABLO'>BOLIVAR-SAN PABLO</option>
    <option value='BOLIVAR-SANTA CATALINA'>BOLIVAR-SANTA CATALINA</option>
    <option value='BOLIVAR-SANTA ROSA'>BOLIVAR-SANTA ROSA</option>
    <option value='BOLIVAR-SANTA ROSA DEL SUR'>BOLIVAR-SANTA ROSA DEL SUR</option>
    <option value='BOLIVAR-SIMITI'>BOLIVAR-SIMITI</option>
    <option value='BOLIVAR-SOPLAVIENTO'>BOLIVAR-SOPLAVIENTO</option>
    <option value='BOLIVAR-TALAIGUA NUEVO'>BOLIVAR-TALAIGUA NUEVO</option>
    <option value='BOLIVAR-TIQUISIO'>BOLIVAR-TIQUISIO</option>
    <option value='BOLIVAR-TURBACO'>BOLIVAR-TURBACO</option>
    <option value='BOLIVAR-TURBANA'>BOLIVAR-TURBANA</option>
    <option value='BOLIVAR-VILLANUEVA'>BOLIVAR-VILLANUEVA</option>
    <option value='BOLIVAR-ZAMBRANO'>BOLIVAR-ZAMBRANO</option>
    <option value='BOYACA-TUNJA'>BOYACA-TUNJA</option>
    <option value='BOYACA-ALMEIDA'>BOYACA-ALMEIDA</option>
    <option value='BOYACA-AQUITANIA'>BOYACA-AQUITANIA</option>
    <option value='BOYACA-ARCABUCO'>BOYACA-ARCABUCO</option>
    <option value='BOYACA-BELEN'>BOYACA-BELEN</option>
    <option value='BOYACA-BERBEO'>BOYACA-BERBEO</option>
    <option value='BOYACA-BETEITIVA'>BOYACA-BETEITIVA</option>
    <option value='BOYACA-BOAVITA'>BOYACA-BOAVITA</option>
    <option value='BOYACA-BOYACA'>BOYACA-BOYACA</option>
    <option value='BOYACA-BRICEÑO'>BOYACA-BRICEÑO</option>
    <option value='BOYACA-BUENAVISTA'>BOYACA-BUENAVISTA</option>
    <option value='BOYACA-BUSBANZA'>BOYACA-BUSBANZA</option>
    <option value='BOYACA-CALDAS'>BOYACA-CALDAS</option>
    <option value='BOYACA-CAMPOHERMOSO'>BOYACA-CAMPOHERMOSO</option>
    <option value='BOYACA-CERINZA'>BOYACA-CERINZA</option>
    <option value='BOYACA-CHINAVITA'>BOYACA-CHINAVITA</option>
    <option value='BOYACA-CHIQUINQUIRA'>BOYACA-CHIQUINQUIRA</option>
    <option value='BOYACA-CHISCAS'>BOYACA-CHISCAS</option>
    <option value='BOYACA-CHITA'>BOYACA-CHITA</option>
    <option value='BOYACA-CHITARAQUE'>BOYACA-CHITARAQUE</option>
    <option value='BOYACA-CHIVATA'>BOYACA-CHIVATA</option>
    <option value='BOYACA-CIENEGA'>BOYACA-CIENEGA</option>
    <option value='BOYACA-COMBITA'>BOYACA-COMBITA</option>
    <option value='BOYACA-COPER'>BOYACA-COPER</option>
    <option value='BOYACA-CORRALES'>BOYACA-CORRALES</option>
    <option value='BOYACA-COVARACHIA'>BOYACA-COVARACHIA</option>
    <option value='BOYACA-CUBARA'>BOYACA-CUBARA</option>
    <option value='BOYACA-CUCAITA'>BOYACA-CUCAITA</option>
    <option value='BOYACA-CUITIVA'>BOYACA-CUITIVA</option>
    <option value='BOYACA-CHIQUIZA'>BOYACA-CHIQUIZA</option>
    <option value='BOYACA-CHIVOR'>BOYACA-CHIVOR</option>
    <option value='BOYACA-DUITAMA'>BOYACA-DUITAMA</option>
    <option value='BOYACA-EL COCUY'>BOYACA-EL COCUY</option>
    <option value='BOYACA-EL ESPINO'>BOYACA-EL ESPINO</option>
    <option value='BOYACA-FIRAVITOBA'>BOYACA-FIRAVITOBA</option>
    <option value='BOYACA-FLORESTA'>BOYACA-FLORESTA</option>
    <option value='BOYACA-GACHANTIVA'>BOYACA-GACHANTIVA</option>
    <option value='BOYACA-GAMEZA'>BOYACA-GAMEZA</option>
    <option value='BOYACA-GARAGOA'>BOYACA-GARAGOA</option>
    <option value='BOYACA-GUACAMAYAS'>BOYACA-GUACAMAYAS</option>
    <option value='BOYACA-GUATEQUE'>BOYACA-GUATEQUE</option>
    <option value='BOYACA-GUAYATA'>BOYACA-GUAYATA</option>
    <option value='BOYACA-GsICAN'>BOYACA-GsICAN</option>
    <option value='BOYACA-IZA'>BOYACA-IZA</option>
    <option value='BOYACA-JENESANO'>BOYACA-JENESANO</option>
    <option value='BOYACA-JERICO'>BOYACA-JERICO</option>
    <option value='BOYACA-LABRANZAGRANDE'>BOYACA-LABRANZAGRANDE</option>
    <option value='BOYACA-LA CAPILLA'>BOYACA-LA CAPILLA</option>
    <option value='BOYACA-LA VICTORIA'>BOYACA-LA VICTORIA</option>
    <option value='BOYACA-LA UVITA'>BOYACA-LA UVITA</option>
    <option value='BOYACA-VILLA DE LEYVA'>BOYACA-VILLA DE LEYVA</option>
    <option value='BOYACA-MACANAL'>BOYACA-MACANAL</option>
    <option value='BOYACA-MARIPI'>BOYACA-MARIPI</option>
    <option value='BOYACA-MIRAFLORES'>BOYACA-MIRAFLORES</option>
    <option value='BOYACA-MONGUA'>BOYACA-MONGUA</option>
    <option value='BOYACA-MONGUI'>BOYACA-MONGUI</option>
    <option value='BOYACA-MONIQUIRA'>BOYACA-MONIQUIRA</option>
    <option value='BOYACA-MOTAVITA'>BOYACA-MOTAVITA</option>
    <option value='BOYACA-MUZO'>BOYACA-MUZO</option>
    <option value='BOYACA-NOBSA'>BOYACA-NOBSA</option>
    <option value='BOYACA-NUEVO COLON'>BOYACA-NUEVO COLON</option>
    <option value='BOYACA-OICATA'>BOYACA-OICATA</option>
    <option value='BOYACA-OTANCHE'>BOYACA-OTANCHE</option>
    <option value='BOYACA-PACHAVITA'>BOYACA-PACHAVITA</option>
    <option value='BOYACA-PAEZ'>BOYACA-PAEZ</option>
    <option value='BOYACA-PAIPA'>BOYACA-PAIPA</option>
    <option value='BOYACA-PAJARITO'>BOYACA-PAJARITO</option>
    <option value='BOYACA-PANQUEBA'>BOYACA-PANQUEBA</option>
    <option value='BOYACA-PAUNA'>BOYACA-PAUNA</option>
    <option value='BOYACA-PAYA'>BOYACA-PAYA</option>
    <option value='BOYACA-PAZ DE RIO'>BOYACA-PAZ DE RIO</option>
    <option value='BOYACA-PESCA'>BOYACA-PESCA</option>
    <option value='BOYACA-PISBA'>BOYACA-PISBA</option>
    <option value='BOYACA-PUERTO BOYACA'>BOYACA-PUERTO BOYACA</option>
    <option value='BOYACA-QUIPAMA'>BOYACA-QUIPAMA</option>
    <option value='BOYACA-RAMIRIQUI'>BOYACA-RAMIRIQUI</option>
    <option value='BOYACA-RAQUIRA'>BOYACA-RAQUIRA</option>
    <option value='BOYACA-RONDON'>BOYACA-RONDON</option>
    <option value='BOYACA-SABOYA'>BOYACA-SABOYA</option>
    <option value='BOYACA-SACHICA'>BOYACA-SACHICA</option>
    <option value='BOYACA-SAMACA'>BOYACA-SAMACA</option>
    <option value='BOYACA-SAN EDUARDO'>BOYACA-SAN EDUARDO</option>
    <option value='BOYACA-SAN JOSE DE PARE'>BOYACA-SAN JOSE DE PARE</option>
    <option value='BOYACA-SAN LUIS DE GACENO'>BOYACA-SAN LUIS DE GACENO</option>
    <option value='BOYACA-SAN MATEO'>BOYACA-SAN MATEO</option>
    <option value='BOYACA-SAN MIGUEL DE SEMA'>BOYACA-SAN MIGUEL DE SEMA</option>
    <option value='BOYACA-SAN PABLO DE BORBUR'>BOYACA-SAN PABLO DE BORBUR</option>
    <option value='BOYACA-SANTANA'>BOYACA-SANTANA</option>
    <option value='BOYACA-SANTA MARIA'>BOYACA-SANTA MARIA</option>
    <option value='BOYACA-SANTA ROSA DE VITERBO'>BOYACA-SANTA ROSA DE VITERBO</option>
    <option value='BOYACA-SANTA SOFIA'>BOYACA-SANTA SOFIA</option>
    <option value='BOYACA-SATIVANORTE'>BOYACA-SATIVANORTE</option>
    <option value='BOYACA-SATIVASUR'>BOYACA-SATIVASUR</option>
    <option value='BOYACA-SIACHOQUE'>BOYACA-SIACHOQUE</option>
    <option value='BOYACA-SOATA'>BOYACA-SOATA</option>
    <option value='BOYACA-SOCOTA'>BOYACA-SOCOTA</option>
    <option value='BOYACA-SOCHA'>BOYACA-SOCHA</option>
    <option value='BOYACA-SOGAMOSO'>BOYACA-SOGAMOSO</option>
    <option value='BOYACA-SOMONDOCO'>BOYACA-SOMONDOCO</option>
    <option value='BOYACA-SORA'>BOYACA-SORA</option>
    <option value='BOYACA-SOTAQUIRA'>BOYACA-SOTAQUIRA</option>
    <option value='BOYACA-SORACA'>BOYACA-SORACA</option>
    <option value='BOYACA-SUSACON'>BOYACA-SUSACON</option>
    <option value='BOYACA-SUTAMARCHAN'>BOYACA-SUTAMARCHAN</option>
    <option value='BOYACA-SUTATENZA'>BOYACA-SUTATENZA</option>
    <option value='BOYACA-TASCO'>BOYACA-TASCO</option>
    <option value='BOYACA-TENZA'>BOYACA-TENZA</option>
    <option value='BOYACA-TIBANA'>BOYACA-TIBANA</option>
    <option value='BOYACA-TIBASOSA'>BOYACA-TIBASOSA</option>
    <option value='BOYACA-TINJACA'>BOYACA-TINJACA</option>
    <option value='BOYACA-TIPACOQUE'>BOYACA-TIPACOQUE</option>
    <option value='BOYACA-TOCA'>BOYACA-TOCA</option>
    <option value='BOYACA-TOGsI'>BOYACA-TOGsI</option>
    <option value='BOYACA-TOPAGA'>BOYACA-TOPAGA</option>
    <option value='BOYACA-TOTA'>BOYACA-TOTA</option>
    <option value='BOYACA-TUNUNGUA'>BOYACA-TUNUNGUA</option>
    <option value='BOYACA-TURMEQUE'>BOYACA-TURMEQUE</option>
    <option value='BOYACA-TUTA'>BOYACA-TUTA</option>
    <option value='BOYACA-TUTAZA'>BOYACA-TUTAZA</option>
    <option value='BOYACA-UMBITA'>BOYACA-UMBITA</option>
    <option value='BOYACA-VENTAQUEMADA'>BOYACA-VENTAQUEMADA</option>
    <option value='BOYACA-VIRACACHA'>BOYACA-VIRACACHA</option>
    <option value='BOYACA-ZETAQUIRA'>BOYACA-ZETAQUIRA</option>
    <option value='CALDAS-MANIZALES'>CALDAS-MANIZALES</option>
    <option value='CALDAS-AGUADAS'>CALDAS-AGUADAS</option>
    <option value='CALDAS-ANSERMA'>CALDAS-ANSERMA</option>
    <option value='CALDAS-ARANZAZU'>CALDAS-ARANZAZU</option>
    <option value='CALDAS-BELALCAZAR'>CALDAS-BELALCAZAR</option>
    <option value='CALDAS-CHINCHINA'>CALDAS-CHINCHINA</option>
    <option value='CALDAS-FILADELFIA'>CALDAS-FILADELFIA</option>
    <option value='CALDAS-LA DORADA'>CALDAS-LA DORADA</option>
    <option value='CALDAS-LA MERCED'>CALDAS-LA MERCED</option>
    <option value='CALDAS-MANZANARES'>CALDAS-MANZANARES</option>
    <option value='CALDAS-MARMATO'>CALDAS-MARMATO</option>
    <option value='CALDAS-MARQUETALIA'>CALDAS-MARQUETALIA</option>
    <option value='CALDAS-MARULANDA'>CALDAS-MARULANDA</option>
    <option value='CALDAS-NEIRA'>CALDAS-NEIRA</option>
    <option value='CALDAS-NORCASIA'>CALDAS-NORCASIA</option>
    <option value='CALDAS-PACORA'>CALDAS-PACORA</option>
    <option value='CALDAS-PALESTINA'>CALDAS-PALESTINA</option>
    <option value='CALDAS-PENSILVANIA'>CALDAS-PENSILVANIA</option>
    <option value='CALDAS-RIOSUCIO'>CALDAS-RIOSUCIO</option>
    <option value='CALDAS-RISARALDA'>CALDAS-RISARALDA</option>
    <option value='CALDAS-SALAMINA'>CALDAS-SALAMINA</option>
    <option value='CALDAS-SAMANA'>CALDAS-SAMANA</option>
    <option value='CALDAS-SAN JOSE'>CALDAS-SAN JOSE</option>
    <option value='CALDAS-SUPIA'>CALDAS-SUPIA</option>
    <option value='CALDAS-VICTORIA'>CALDAS-VICTORIA</option>
    <option value='CALDAS-VILLAMARIA'>CALDAS-VILLAMARIA</option>
    <option value='CALDAS-VITERBO'>CALDAS-VITERBO</option>
    <option value='CAQUETA-FLORENCIA'>CAQUETA-FLORENCIA</option>
    <option value='CAQUETA-ALBANIA'>CAQUETA-ALBANIA</option>
    <option value='CAQUETA-BELEN DE LOS ANDAQUIES'>CAQUETA-BELEN DE LOS ANDAQUIES</option>
    <option value='CAQUETA-CARTAGENA DEL CHAIRA'>CAQUETA-CARTAGENA DEL CHAIRA</option>
    <option value='CAQUETA-CURILLO'>CAQUETA-CURILLO</option>
    <option value='CAQUETA-EL DONCELLO'>CAQUETA-EL DONCELLO</option>
    <option value='CAQUETA-EL PAUJIL'>CAQUETA-EL PAUJIL</option>
    <option value='CAQUETA-LA MONTAÑITA'>CAQUETA-LA MONTAÑITA</option>
    <option value='CAQUETA-MILAN'>CAQUETA-MILAN</option>
    <option value='CAQUETA-MORELIA'>CAQUETA-MORELIA</option>
    <option value='CAQUETA-PUERTO RICO'>CAQUETA-PUERTO RICO</option>
    <option value='CAQUETA-SAN JOSE DEL FRAGUA'>CAQUETA-SAN JOSE DEL FRAGUA</option>
    <option value='CAQUETA-SAN VICENTE DEL CAGUAN'>CAQUETA-SAN VICENTE DEL CAGUAN</option>
    <option value='CAQUETA-SOLANO'>CAQUETA-SOLANO</option>
    <option value='CAQUETA-SOLITA'>CAQUETA-SOLITA</option>
    <option value='CAQUETA-VALPARAISO'>CAQUETA-VALPARAISO</option>
    <option value='CAUCA-POPAYAN'>CAUCA-POPAYAN</option>
    <option value='CAUCA-ALMAGUER'>CAUCA-ALMAGUER</option>
    <option value='CAUCA-ARGELIA'>CAUCA-ARGELIA</option>
    <option value='CAUCA-BALBOA'>CAUCA-BALBOA</option>
    <option value='CAUCA-BOLIVAR'>CAUCA-BOLIVAR</option>
    <option value='CAUCA-BUENOS AIRES'>CAUCA-BUENOS AIRES</option>
    <option value='CAUCA-CAJIBIO'>CAUCA-CAJIBIO</option>
    <option value='CAUCA-CALDONO'>CAUCA-CALDONO</option>
    <option value='CAUCA-CALOTO'>CAUCA-CALOTO</option>
    <option value='CAUCA-CORINTO'>CAUCA-CORINTO</option>
    <option value='CAUCA-EL TAMBO'>CAUCA-EL TAMBO</option>
    <option value='CAUCA-FLORENCIA'>CAUCA-FLORENCIA</option>
    <option value='CAUCA-GUACHENE'>CAUCA-GUACHENE</option>
    <option value='CAUCA-GUAPI'>CAUCA-GUAPI</option>
    <option value='CAUCA-INZA'>CAUCA-INZA</option>
    <option value='CAUCA-JAMBALO'>CAUCA-JAMBALO</option>
    <option value='CAUCA-LA SIERRA'>CAUCA-LA SIERRA</option>
    <option value='CAUCA-LA VEGA'>CAUCA-LA VEGA</option>
    <option value='CAUCA-LOPEZ'>CAUCA-LOPEZ</option>
    <option value='CAUCA-MERCADERES'>CAUCA-MERCADERES</option>
    <option value='CAUCA-MIRANDA'>CAUCA-MIRANDA</option>
    <option value='CAUCA-MORALES'>CAUCA-MORALES</option>
    <option value='CAUCA-PADILLA'>CAUCA-PADILLA</option>
    <option value='CAUCA-PAEZ'>CAUCA-PAEZ</option>
    <option value='CAUCA-PATIA'>CAUCA-PATIA</option>
    <option value='CAUCA-PIAMONTE'>CAUCA-PIAMONTE</option>
    <option value='CAUCA-PIENDAMO'>CAUCA-PIENDAMO</option>
    <option value='CAUCA-PUERTO TEJADA'>CAUCA-PUERTO TEJADA</option>
    <option value='CAUCA-PURACE'>CAUCA-PURACE</option>
    <option value='CAUCA-ROSAS'>CAUCA-ROSAS</option>
    <option value='CAUCA-SAN SEBASTIAN'>CAUCA-SAN SEBASTIAN</option>
    <option value='CAUCA-SANTANDER DE QUILICHAO'>CAUCA-SANTANDER DE QUILICHAO</option>
    <option value='CAUCA-SANTA ROSA'>CAUCA-SANTA ROSA</option>
    <option value='CAUCA-SILVIA'>CAUCA-SILVIA</option>
    <option value='CAUCA-SOTARA'>CAUCA-SOTARA</option>
    <option value='CAUCA-SUAREZ'>CAUCA-SUAREZ</option>
    <option value='CAUCA-SUCRE'>CAUCA-SUCRE</option>
    <option value='CAUCA-TIMBIO'>CAUCA-TIMBIO</option>
    <option value='CAUCA-TIMBIQUI'>CAUCA-TIMBIQUI</option>
    <option value='CAUCA-TORIBIO'>CAUCA-TORIBIO</option>
    <option value='CAUCA-TOTORO'>CAUCA-TOTORO</option>
    <option value='CAUCA-VILLA RICA'>CAUCA-VILLA RICA</option>
    <option value='CESAR-VALLEDUPAR'>CESAR-VALLEDUPAR</option>
    <option value='CESAR-AGUACHICA'>CESAR-AGUACHICA</option>
    <option value='CESAR-AGUSTIN CODAZZI'>CESAR-AGUSTIN CODAZZI</option>
    <option value='CESAR-ASTREA'>CESAR-ASTREA</option>
    <option value='CESAR-BECERRIL'>CESAR-BECERRIL</option>
    <option value='CESAR-BOSCONIA'>CESAR-BOSCONIA</option>
    <option value='CESAR-CHIMICHAGUA'>CESAR-CHIMICHAGUA</option>
    <option value='CESAR-CHIRIGUANA'>CESAR-CHIRIGUANA</option>
    <option value='CESAR-CURUMANI'>CESAR-CURUMANI</option>
    <option value='CESAR-EL COPEY'>CESAR-EL COPEY</option>
    <option value='CESAR-EL PASO'>CESAR-EL PASO</option>
    <option value='CESAR-GAMARRA'>CESAR-GAMARRA</option>
    <option value='CESAR-GONZALEZ'>CESAR-GONZALEZ</option>
    <option value='CESAR-LA GLORIA'>CESAR-LA GLORIA</option>
    <option value='CESAR-LA JAGUA DE IBIRICO'>CESAR-LA JAGUA DE IBIRICO</option>
    <option value='CESAR-MANAURE'>CESAR-MANAURE</option>
    <option value='CESAR-PAILITAS'>CESAR-PAILITAS</option>
    <option value='CESAR-PELAYA'>CESAR-PELAYA</option>
    <option value='CESAR-PUEBLO BELLO'>CESAR-PUEBLO BELLO</option>
    <option value='CESAR-RIO DE ORO'>CESAR-RIO DE ORO</option>
    <option value='CESAR-LA PAZ'>CESAR-LA PAZ</option>
    <option value='CESAR-SAN ALBERTO'>CESAR-SAN ALBERTO</option>
    <option value='CESAR-SAN DIEGO'>CESAR-SAN DIEGO</option>
    <option value='CESAR-SAN MARTIN'>CESAR-SAN MARTIN</option>
    <option value='CESAR-TAMALAMEQUE'>CESAR-TAMALAMEQUE</option>
    <option value='CORDOBA-MONTERIA'>CORDOBA-MONTERIA</option>
    <option value='CORDOBA-AYAPEL'>CORDOBA-AYAPEL</option>
    <option value='CORDOBA-BUENAVISTA'>CORDOBA-BUENAVISTA</option>
    <option value='CORDOBA-CANALETE'>CORDOBA-CANALETE</option>
    <option value='CORDOBA-CERETE'>CORDOBA-CERETE</option>
    <option value='CORDOBA-CHIMA'>CORDOBA-CHIMA</option>
    <option value='CORDOBA-CHINU'>CORDOBA-CHINU</option>
    <option value='CORDOBA-CIENAGA DE ORO'>CORDOBA-CIENAGA DE ORO</option>
    <option value='CORDOBA-COTORRA'>CORDOBA-COTORRA</option>
    <option value='CORDOBA-LA APARTADA'>CORDOBA-LA APARTADA</option>
    <option value='CORDOBA-LORICA'>CORDOBA-LORICA</option>
    <option value='CORDOBA-LOS CORDOBAS'>CORDOBA-LOS CORDOBAS</option>
    <option value='CORDOBA-MOMIL'>CORDOBA-MOMIL</option>
    <option value='CORDOBA-MONTELIBANO'>CORDOBA-MONTELIBANO</option>
    <option value='CORDOBA-MOÑITOS'>CORDOBA-MOÑITOS</option>
    <option value='CORDOBA-PLANETA RICA'>CORDOBA-PLANETA RICA</option>
    <option value='CORDOBA-PUEBLO NUEVO'>CORDOBA-PUEBLO NUEVO</option>
    <option value='CORDOBA-PUERTO ESCONDIDO'>CORDOBA-PUERTO ESCONDIDO</option>
    <option value='CORDOBA-PUERTO LIBERTADOR'>CORDOBA-PUERTO LIBERTADOR</option>
    <option value='CORDOBA-PURISIMA'>CORDOBA-PURISIMA</option>
    <option value='CORDOBA-SAHAGUN'>CORDOBA-SAHAGUN</option>
    <option value='CORDOBA-SAN ANDRES SOTAVENTO'>CORDOBA-SAN ANDRES SOTAVENTO</option>
    <option value='CORDOBA-SAN ANTERO'>CORDOBA-SAN ANTERO</option>
    <option value='CORDOBA-SAN BERNARDO DEL VIENTO'>CORDOBA-SAN BERNARDO DEL VIENTO</option>
    <option value='CORDOBA-SAN CARLOS'>CORDOBA-SAN CARLOS</option>
    <option value='CORDOBA-SAN PELAYO'>CORDOBA-SAN PELAYO</option>
    <option value='CORDOBA-TIERRALTA'>CORDOBA-TIERRALTA</option>
    <option value='CORDOBA-VALENCIA'>CORDOBA-VALENCIA</option>
    <option value='CUNDINAMARCA-AGUA DE DIOS'>CUNDINAMARCA-AGUA DE DIOS</option>
    <option value='CUNDINAMARCA-ALBAN'>CUNDINAMARCA-ALBAN</option>
    <option value='CUNDINAMARCA-ANAPOIMA'>CUNDINAMARCA-ANAPOIMA</option>
    <option value='CUNDINAMARCA-ANOLAIMA'>CUNDINAMARCA-ANOLAIMA</option>
    <option value='CUNDINAMARCA-ARBELAEZ'>CUNDINAMARCA-ARBELAEZ</option>
    <option value='CUNDINAMARCA-BELTRAN'>CUNDINAMARCA-BELTRAN</option>
    <option value='CUNDINAMARCA-BITUIMA'>CUNDINAMARCA-BITUIMA</option>
    <option value='CUNDINAMARCA-BOJACA'>CUNDINAMARCA-BOJACA</option>
    <option value='CUNDINAMARCA-CABRERA'>CUNDINAMARCA-CABRERA</option>
    <option value='CUNDINAMARCA-CACHIPAY'>CUNDINAMARCA-CACHIPAY</option>
    <option value='CUNDINAMARCA-CAJICA'>CUNDINAMARCA-CAJICA</option>
    <option value='CUNDINAMARCA-CAPARRAPI'>CUNDINAMARCA-CAPARRAPI</option>
    <option value='CUNDINAMARCA-CAQUEZA'>CUNDINAMARCA-CAQUEZA</option>
    <option value='CUNDINAMARCA-CARMEN DE CARUPA'>CUNDINAMARCA-CARMEN DE CARUPA</option>
    <option value='CUNDINAMARCA-CHAGUANI'>CUNDINAMARCA-CHAGUANI</option>
    <option value='CUNDINAMARCA-CHIA'>CUNDINAMARCA-CHIA</option>
    <option value='CUNDINAMARCA-CHIPAQUE'>CUNDINAMARCA-CHIPAQUE</option>
    <option value='CUNDINAMARCA-CHOACHI'>CUNDINAMARCA-CHOACHI</option>
    <option value='CUNDINAMARCA-CHOCONTA'>CUNDINAMARCA-CHOCONTA</option>
    <option value='CUNDINAMARCA-COGUA'>CUNDINAMARCA-COGUA</option>
    <option value='CUNDINAMARCA-COTA'>CUNDINAMARCA-COTA</option>
    <option value='CUNDINAMARCA-CUCUNUBA'>CUNDINAMARCA-CUCUNUBA</option>
    <option value='CUNDINAMARCA-EL COLEGIO'>CUNDINAMARCA-EL COLEGIO</option>
    <option value='CUNDINAMARCA-EL PEÑON'>CUNDINAMARCA-EL PEÑON</option>
    <option value='CUNDINAMARCA-EL ROSAL'>CUNDINAMARCA-EL ROSAL</option>
    <option value='CUNDINAMARCA-FACATATIVA'>CUNDINAMARCA-FACATATIVA</option>
    <option value='CUNDINAMARCA-FOMEQUE'>CUNDINAMARCA-FOMEQUE</option>
    <option value='CUNDINAMARCA-FOSCA'>CUNDINAMARCA-FOSCA</option>
    <option value='CUNDINAMARCA-FUNZA'>CUNDINAMARCA-FUNZA</option>
    <option value='CUNDINAMARCA-FUQUENE'>CUNDINAMARCA-FUQUENE</option>
    <option value='CUNDINAMARCA-FUSAGASUGA'>CUNDINAMARCA-FUSAGASUGA</option>
    <option value='CUNDINAMARCA-GACHALA'>CUNDINAMARCA-GACHALA</option>
    <option value='CUNDINAMARCA-GACHANCIPA'>CUNDINAMARCA-GACHANCIPA</option>
    <option value='CUNDINAMARCA-GACHETA'>CUNDINAMARCA-GACHETA</option>
    <option value='CUNDINAMARCA-GAMA'>CUNDINAMARCA-GAMA</option>
    <option value='CUNDINAMARCA-GIRARDOT'>CUNDINAMARCA-GIRARDOT</option>
    <option value='CUNDINAMARCA-GRANADA'>CUNDINAMARCA-GRANADA</option>
    <option value='CUNDINAMARCA-GUACHETA'>CUNDINAMARCA-GUACHETA</option>
    <option value='CUNDINAMARCA-GUADUAS'>CUNDINAMARCA-GUADUAS</option>
    <option value='CUNDINAMARCA-GUASCA'>CUNDINAMARCA-GUASCA</option>
    <option value='CUNDINAMARCA-GUATAQUI'>CUNDINAMARCA-GUATAQUI</option>
    <option value='CUNDINAMARCA-GUATAVITA'>CUNDINAMARCA-GUATAVITA</option>
    <option value='CUNDINAMARCA-GUAYABAL DE SIQUIMA'>CUNDINAMARCA-GUAYABAL DE SIQUIMA</option>
    <option value='CUNDINAMARCA-GUAYABETAL'>CUNDINAMARCA-GUAYABETAL</option>
    <option value='CUNDINAMARCA-GUTIERREZ'>CUNDINAMARCA-GUTIERREZ</option>
    <option value='CUNDINAMARCA-JERUSALEN'>CUNDINAMARCA-JERUSALEN</option>
    <option value='CUNDINAMARCA-JUNIN'>CUNDINAMARCA-JUNIN</option>
    <option value='CUNDINAMARCA-LA CALERA'>CUNDINAMARCA-LA CALERA</option>
    <option value='CUNDINAMARCA-LA MESA'>CUNDINAMARCA-LA MESA</option>
    <option value='CUNDINAMARCA-LA PALMA'>CUNDINAMARCA-LA PALMA</option>
    <option value='CUNDINAMARCA-LA PEÑA'>CUNDINAMARCA-LA PEÑA</option>
    <option value='CUNDINAMARCA-LA VEGA'>CUNDINAMARCA-LA VEGA</option>
    <option value='CUNDINAMARCA-LENGUAZAQUE'>CUNDINAMARCA-LENGUAZAQUE</option>
    <option value='CUNDINAMARCA-MACHETA'>CUNDINAMARCA-MACHETA</option>
    <option value='CUNDINAMARCA-MADRID'>CUNDINAMARCA-MADRID</option>
    <option value='CUNDINAMARCA-MANTA'>CUNDINAMARCA-MANTA</option>
    <option value='CUNDINAMARCA-MEDINA'>CUNDINAMARCA-MEDINA</option>
    <option value='CUNDINAMARCA-MOSQUERA'>CUNDINAMARCA-MOSQUERA</option>
    <option value='CUNDINAMARCA-NARIÑO'>CUNDINAMARCA-NARIÑO</option>
    <option value='CUNDINAMARCA-NEMOCON'>CUNDINAMARCA-NEMOCON</option>
    <option value='CUNDINAMARCA-NILO'>CUNDINAMARCA-NILO</option>
    <option value='CUNDINAMARCA-NIMAIMA'>CUNDINAMARCA-NIMAIMA</option>
    <option value='CUNDINAMARCA-NOCAIMA'>CUNDINAMARCA-NOCAIMA</option>
    <option value='CUNDINAMARCA-VENECIA'>CUNDINAMARCA-VENECIA</option>
    <option value='CUNDINAMARCA-PACHO'>CUNDINAMARCA-PACHO</option>
    <option value='CUNDINAMARCA-PAIME'>CUNDINAMARCA-PAIME</option>
    <option value='CUNDINAMARCA-PANDI'>CUNDINAMARCA-PANDI</option>
    <option value='CUNDINAMARCA-PARATEBUENO'>CUNDINAMARCA-PARATEBUENO</option>
    <option value='CUNDINAMARCA-PASCA'>CUNDINAMARCA-PASCA</option>
    <option value='CUNDINAMARCA-PUERTO SALGAR'>CUNDINAMARCA-PUERTO SALGAR</option>
    <option value='CUNDINAMARCA-PULI'>CUNDINAMARCA-PULI</option>
    <option value='CUNDINAMARCA-QUEBRADANEGRA'>CUNDINAMARCA-QUEBRADANEGRA</option>
    <option value='CUNDINAMARCA-QUETAME'>CUNDINAMARCA-QUETAME</option>
    <option value='CUNDINAMARCA-QUIPILE'>CUNDINAMARCA-QUIPILE</option>
    <option value='CUNDINAMARCA-APULO'>CUNDINAMARCA-APULO</option>
    <option value='CUNDINAMARCA-RICAURTE'>CUNDINAMARCA-RICAURTE</option>
    <option value='CUNDINAMARCA-SAN ANTONIO DEL TEQUENDAMA'>CUNDINAMARCA-SAN ANTONIO DEL TEQUENDAMA</option>
    <option value='CUNDINAMARCA-SAN BERNARDO'>CUNDINAMARCA-SAN BERNARDO</option>
    <option value='CUNDINAMARCA-SAN CAYETANO'>CUNDINAMARCA-SAN CAYETANO</option>
    <option value='CUNDINAMARCA-SAN FRANCISCO'>CUNDINAMARCA-SAN FRANCISCO</option>
    <option value='CUNDINAMARCA-SAN JUAN DE RIO SECO'>CUNDINAMARCA-SAN JUAN DE RIO SECO</option>
    <option value='CUNDINAMARCA-SASAIMA'>CUNDINAMARCA-SASAIMA</option>
    <option value='CUNDINAMARCA-SESQUILE'>CUNDINAMARCA-SESQUILE</option>
    <option value='CUNDINAMARCA-SIBATE'>CUNDINAMARCA-SIBATE</option>
    <option value='CUNDINAMARCA-SILVANIA'>CUNDINAMARCA-SILVANIA</option>
    <option value='CUNDINAMARCA-SIMIJACA'>CUNDINAMARCA-SIMIJACA</option>
    <option value='CUNDINAMARCA-SOACHA'>CUNDINAMARCA-SOACHA</option>
    <option value='CUNDINAMARCA-SOPO'>CUNDINAMARCA-SOPO</option>
    <option value='CUNDINAMARCA-SUBACHOQUE'>CUNDINAMARCA-SUBACHOQUE</option>
    <option value='CUNDINAMARCA-SUESCA'>CUNDINAMARCA-SUESCA</option>
    <option value='CUNDINAMARCA-SUPATA'>CUNDINAMARCA-SUPATA</option>
    <option value='CUNDINAMARCA-SUSA'>CUNDINAMARCA-SUSA</option>
    <option value='CUNDINAMARCA-SUTATAUSA'>CUNDINAMARCA-SUTATAUSA</option>
    <option value='CUNDINAMARCA-TABIO'>CUNDINAMARCA-TABIO</option>
    <option value='CUNDINAMARCA-TAUSA'>CUNDINAMARCA-TAUSA</option>
    <option value='CUNDINAMARCA-TENA'>CUNDINAMARCA-TENA</option>
    <option value='CUNDINAMARCA-TENJO'>CUNDINAMARCA-TENJO</option>
    <option value='CUNDINAMARCA-TIBACUY'>CUNDINAMARCA-TIBACUY</option>
    <option value='CUNDINAMARCA-TIBIRITA'>CUNDINAMARCA-TIBIRITA</option>
    <option value='CUNDINAMARCA-TOCAIMA'>CUNDINAMARCA-TOCAIMA</option>
    <option value='CUNDINAMARCA-TOCANCIPA'>CUNDINAMARCA-TOCANCIPA</option>
    <option value='CUNDINAMARCA-TOPAIPI'>CUNDINAMARCA-TOPAIPI</option>
    <option value='CUNDINAMARCA-UBALA'>CUNDINAMARCA-UBALA</option>
    <option value='CUNDINAMARCA-UBAQUE'>CUNDINAMARCA-UBAQUE</option>
    <option value='CUNDINAMARCA-VILLA DE SAN DIEGO DE UBATE'>CUNDINAMARCA-VILLA DE SAN DIEGO DE UBATE</option>
    <option value='CUNDINAMARCA-UNE'>CUNDINAMARCA-UNE</option>
    <option value='CUNDINAMARCA-UTICA'>CUNDINAMARCA-UTICA</option>
    <option value='CUNDINAMARCA-VERGARA'>CUNDINAMARCA-VERGARA</option>
    <option value='CUNDINAMARCA-VIANI'>CUNDINAMARCA-VIANI</option>
    <option value='CUNDINAMARCA-VILLAGOMEZ'>CUNDINAMARCA-VILLAGOMEZ</option>
    <option value='CUNDINAMARCA-VILLAPINZON'>CUNDINAMARCA-VILLAPINZON</option>
    <option value='CUNDINAMARCA-VILLETA'>CUNDINAMARCA-VILLETA</option>
    <option value='CUNDINAMARCA-VIOTA'>CUNDINAMARCA-VIOTA</option>
    <option value='CUNDINAMARCA-YACOPI'>CUNDINAMARCA-YACOPI</option>
    <option value='CUNDINAMARCA-ZIPACON'>CUNDINAMARCA-ZIPACON</option>
    <option value='CUNDINAMARCA-ZIPAQUIRA'>CUNDINAMARCA-ZIPAQUIRA</option>
    <option value='CHOCO-QUIBDO'>CHOCO-QUIBDO</option>
    <option value='CHOCO-ACANDI'>CHOCO-ACANDI</option>
    <option value='CHOCO-ALTO BAUDO'>CHOCO-ALTO BAUDO</option>
    <option value='CHOCO-ATRATO'>CHOCO-ATRATO</option>
    <option value='CHOCO-BAGADO'>CHOCO-BAGADO</option>
    <option value='CHOCO-BAHIA SOLANO'>CHOCO-BAHIA SOLANO</option>
    <option value='CHOCO-BAJO BAUDO'>CHOCO-BAJO BAUDO</option>
    <option value='CHOCO-BOJAYA'>CHOCO-BOJAYA</option>
    <option value='CHOCO-EL CANTON DEL SAN PABLO'>CHOCO-EL CANTON DEL SAN PABLO</option>
    <option value='CHOCO-CARMEN DEL DARIEN'>CHOCO-CARMEN DEL DARIEN</option>
    <option value='CHOCO-CERTEGUI'>CHOCO-CERTEGUI</option>
    <option value='CHOCO-CONDOTO'>CHOCO-CONDOTO</option>
    <option value='CHOCO-EL CARMEN DE ATRATO'>CHOCO-EL CARMEN DE ATRATO</option>
    <option value='CHOCO-EL LITORAL DEL SAN JUAN'>CHOCO-EL LITORAL DEL SAN JUAN</option>
    <option value='CHOCO-ISTMINA'>CHOCO-ISTMINA</option>
    <option value='CHOCO-JURADO'>CHOCO-JURADO</option>
    <option value='CHOCO-LLORO'>CHOCO-LLORO</option>
    <option value='CHOCO-MEDIO ATRATO'>CHOCO-MEDIO ATRATO</option>
    <option value='CHOCO-MEDIO BAUDO'>CHOCO-MEDIO BAUDO</option>
    <option value='CHOCO-MEDIO SAN JUAN'>CHOCO-MEDIO SAN JUAN</option>
    <option value='CHOCO-NOVITA'>CHOCO-NOVITA</option>
    <option value='CHOCO-NUQUI'>CHOCO-NUQUI</option>
    <option value='CHOCO-RIO IRO'>CHOCO-RIO IRO</option>
    <option value='CHOCO-RIO QUITO'>CHOCO-RIO QUITO</option>
    <option value='CHOCO-RIOSUCIO'>CHOCO-RIOSUCIO</option>
    <option value='CHOCO-SAN JOSE DEL PALMAR'>CHOCO-SAN JOSE DEL PALMAR</option>
    <option value='CHOCO-SIPI'>CHOCO-SIPI</option>
    <option value='CHOCO-TADO'>CHOCO-TADO</option>
    <option value='CHOCO-UNGUIA'>CHOCO-UNGUIA</option>
    <option value='CHOCO-UNION PANAMERICANA'>CHOCO-UNION PANAMERICANA</option>
    <option value='HUILA-NEIVA'>HUILA-NEIVA</option>
    <option value='HUILA-ACEVEDO'>HUILA-ACEVEDO</option>
    <option value='HUILA-AGRADO'>HUILA-AGRADO</option>
    <option value='HUILA-AIPE'>HUILA-AIPE</option>
    <option value='HUILA-ALGECIRAS'>HUILA-ALGECIRAS</option>
    <option value='HUILA-ALTAMIRA'>HUILA-ALTAMIRA</option>
    <option value='HUILA-BARAYA'>HUILA-BARAYA</option>
    <option value='HUILA-CAMPOALEGRE'>HUILA-CAMPOALEGRE</option>
    <option value='HUILA-COLOMBIA'>HUILA-COLOMBIA</option>
    <option value='HUILA-ELIAS'>HUILA-ELIAS</option>
    <option value='HUILA-GARZON'>HUILA-GARZON</option>
    <option value='HUILA-GIGANTE'>HUILA-GIGANTE</option>
    <option value='HUILA-GUADALUPE'>HUILA-GUADALUPE</option>
    <option value='HUILA-HOBO'>HUILA-HOBO</option>
    <option value='HUILA-IQUIRA'>HUILA-IQUIRA</option>
    <option value='HUILA-ISNOS'>HUILA-ISNOS</option>
    <option value='HUILA-LA ARGENTINA'>HUILA-LA ARGENTINA</option>
    <option value='HUILA-LA PLATA'>HUILA-LA PLATA</option>
    <option value='HUILA-NATAGA'>HUILA-NATAGA</option>
    <option value='HUILA-OPORAPA'>HUILA-OPORAPA</option>
    <option value='HUILA-PAICOL'>HUILA-PAICOL</option>
    <option value='HUILA-PALERMO'>HUILA-PALERMO</option>
    <option value='HUILA-PALESTINA'>HUILA-PALESTINA</option>
    <option value='HUILA-PITAL'>HUILA-PITAL</option>
    <option value='HUILA-PITALITO'>HUILA-PITALITO</option>
    <option value='HUILA-RIVERA'>HUILA-RIVERA</option>
    <option value='HUILA-SALADOBLANCO'>HUILA-SALADOBLANCO</option>
    <option value='HUILA-SAN AGUSTIN'>HUILA-SAN AGUSTIN</option>
    <option value='HUILA-SANTA MARIA'>HUILA-SANTA MARIA</option>
    <option value='HUILA-SUAZA'>HUILA-SUAZA</option>
    <option value='HUILA-TARQUI'>HUILA-TARQUI</option>
    <option value='HUILA-TESALIA'>HUILA-TESALIA</option>
    <option value='HUILA-TELLO'>HUILA-TELLO</option>
    <option value='HUILA-TERUEL'>HUILA-TERUEL</option>
    <option value='HUILA-TIMANA'>HUILA-TIMANA</option>
    <option value='HUILA-VILLAVIEJA'>HUILA-VILLAVIEJA</option>
    <option value='HUILA-YAGUARA'>HUILA-YAGUARA</option>
    <option value='LA GUAJIRA-RIOHACHA'>LA GUAJIRA-RIOHACHA</option>
    <option value='LA GUAJIRA-ALBANIA'>LA GUAJIRA-ALBANIA</option>
    <option value='LA GUAJIRA-BARRANCAS'>LA GUAJIRA-BARRANCAS</option>
    <option value='LA GUAJIRA-DIBULLA'>LA GUAJIRA-DIBULLA</option>
    <option value='LA GUAJIRA-DISTRACCION'>LA GUAJIRA-DISTRACCION</option>
    <option value='LA GUAJIRA-EL MOLINO'>LA GUAJIRA-EL MOLINO</option>
    <option value='LA GUAJIRA-FONSECA'>LA GUAJIRA-FONSECA</option>
    <option value='LA GUAJIRA-HATONUEVO'>LA GUAJIRA-HATONUEVO</option>
    <option value='LA GUAJIRA-LA JAGUA DEL PILAR'>LA GUAJIRA-LA JAGUA DEL PILAR</option>
    <option value='LA GUAJIRA-MAICAO'>LA GUAJIRA-MAICAO</option>
    <option value='LA GUAJIRA-MANAURE'>LA GUAJIRA-MANAURE</option>
    <option value='LA GUAJIRA-SAN JUAN DEL CESAR'>LA GUAJIRA-SAN JUAN DEL CESAR</option>
    <option value='LA GUAJIRA-URIBIA'>LA GUAJIRA-URIBIA</option>
    <option value='LA GUAJIRA-URUMITA'>LA GUAJIRA-URUMITA</option>
    <option value='LA GUAJIRA-VILLANUEVA'>LA GUAJIRA-VILLANUEVA</option>
    <option value='MAGDALENA-SANTA MARTA'>MAGDALENA-SANTA MARTA</option>
    <option value='MAGDALENA-ALGARROBO'>MAGDALENA-ALGARROBO</option>
    <option value='MAGDALENA-ARACATACA'>MAGDALENA-ARACATACA</option>
    <option value='MAGDALENA-ARIGUANI'>MAGDALENA-ARIGUANI</option>
    <option value='MAGDALENA-CERRO SAN ANTONIO'>MAGDALENA-CERRO SAN ANTONIO</option>
    <option value='MAGDALENA-CHIBOLO'>MAGDALENA-CHIBOLO</option>
    <option value='MAGDALENA-CIENAGA'>MAGDALENA-CIENAGA</option>
    <option value='MAGDALENA-CONCORDIA'>MAGDALENA-CONCORDIA</option>
    <option value='MAGDALENA-EL BANCO'>MAGDALENA-EL BANCO</option>
    <option value='MAGDALENA-EL PIÑON'>MAGDALENA-EL PIÑON</option>
    <option value='MAGDALENA-EL RETEN'>MAGDALENA-EL RETEN</option>
    <option value='MAGDALENA-FUNDACION'>MAGDALENA-FUNDACION</option>
    <option value='MAGDALENA-GUAMAL'>MAGDALENA-GUAMAL</option>
    <option value='MAGDALENA-NUEVA GRANADA'>MAGDALENA-NUEVA GRANADA</option>
    <option value='MAGDALENA-PEDRAZA'>MAGDALENA-PEDRAZA</option>
    <option value='MAGDALENA-PIJIÑO DEL CARMEN'>MAGDALENA-PIJIÑO DEL CARMEN</option>
    <option value='MAGDALENA-PIVIJAY'>MAGDALENA-PIVIJAY</option>
    <option value='MAGDALENA-PLATO'>MAGDALENA-PLATO</option>
    <option value='MAGDALENA-PUEBLOVIEJO'>MAGDALENA-PUEBLOVIEJO</option>
    <option value='MAGDALENA-REMOLINO'>MAGDALENA-REMOLINO</option>
    <option value='MAGDALENA-SABANAS DE SAN ANGEL'>MAGDALENA-SABANAS DE SAN ANGEL</option>
    <option value='MAGDALENA-SALAMINA'>MAGDALENA-SALAMINA</option>
    <option value='MAGDALENA-SAN SEBASTIAN DE BUENAVISTA'>MAGDALENA-SAN SEBASTIAN DE BUENAVISTA</option>
    <option value='MAGDALENA-SAN ZENON'>MAGDALENA-SAN ZENON</option>
    <option value='MAGDALENA-SANTA ANA'>MAGDALENA-SANTA ANA</option>
    <option value='MAGDALENA-SANTA BARBARA DE PINTO'>MAGDALENA-SANTA BARBARA DE PINTO</option>
    <option value='MAGDALENA-SITIONUEVO'>MAGDALENA-SITIONUEVO</option>
    <option value='MAGDALENA-TENERIFE'>MAGDALENA-TENERIFE</option>
    <option value='MAGDALENA-ZAPAYAN'>MAGDALENA-ZAPAYAN</option>
    <option value='MAGDALENA-ZONA BANANERA'>MAGDALENA-ZONA BANANERA</option>
    <option value='META-VILLAVICENCIO'>META-VILLAVICENCIO</option>
    <option value='META-ACACIAS'>META-ACACIAS</option>
    <option value='META-BARRANCA DE UPIA'>META-BARRANCA DE UPIA</option>
    <option value='META-CABUYARO'>META-CABUYARO</option>
    <option value='META-CASTILLA LA NUEVA'>META-CASTILLA LA NUEVA</option>
    <option value='META-CUBARRAL'>META-CUBARRAL</option>
    <option value='META-CUMARAL'>META-CUMARAL</option>
    <option value='META-EL CALVARIO'>META-EL CALVARIO</option>
    <option value='META-EL CASTILLO'>META-EL CASTILLO</option>
    <option value='META-EL DORADO'>META-EL DORADO</option>
    <option value='META-FUENTE DE ORO'>META-FUENTE DE ORO</option>
    <option value='META-GRANADA'>META-GRANADA</option>
    <option value='META-GUAMAL'>META-GUAMAL</option>
    <option value='META-MAPIRIPAN'>META-MAPIRIPAN</option>
    <option value='META-MESETAS'>META-MESETAS</option>
    <option value='META-LA MACARENA'>META-LA MACARENA</option>
    <option value='META-URIBE'>META-URIBE</option>
    <option value='META-LEJANIAS'>META-LEJANIAS</option>
    <option value='META-PUERTO CONCORDIA'>META-PUERTO CONCORDIA</option>
    <option value='META-PUERTO GAITAN'>META-PUERTO GAITAN</option>
    <option value='META-PUERTO LOPEZ'>META-PUERTO LOPEZ</option>
    <option value='META-PUERTO LLERAS'>META-PUERTO LLERAS</option>
    <option value='META-PUERTO RICO'>META-PUERTO RICO</option>
    <option value='META-RESTREPO'>META-RESTREPO</option>
    <option value='META-SAN CARLOS DE GUAROA'>META-SAN CARLOS DE GUAROA</option>
    <option value='META-SAN JUAN DE ARAMA'>META-SAN JUAN DE ARAMA</option>
    <option value='META-SAN JUANITO'>META-SAN JUANITO</option>
    <option value='META-SAN MARTIN'>META-SAN MARTIN</option>
    <option value='META-VISTAHERMOSA'>META-VISTAHERMOSA</option>
    <option value='NARIÑO-PASTO'>NARIÑO-PASTO</option>
    <option value='NARIÑO-ALBAN'>NARIÑO-ALBAN</option>
    <option value='NARIÑO-ALDANA'>NARIÑO-ALDANA</option>
    <option value='NARIÑO-ANCUYA'>NARIÑO-ANCUYA</option>
    <option value='NARIÑO-ARBOLEDA'>NARIÑO-ARBOLEDA</option>
    <option value='NARIÑO-BARBACOAS'>NARIÑO-BARBACOAS</option>
    <option value='NARIÑO-BELEN'>NARIÑO-BELEN</option>
    <option value='NARIÑO-BUESACO'>NARIÑO-BUESACO</option>
    <option value='NARIÑO-COLON'>NARIÑO-COLON</option>
    <option value='NARIÑO-CONSACA'>NARIÑO-CONSACA</option>
    <option value='NARIÑO-CONTADERO'>NARIÑO-CONTADERO</option>
    <option value='NARIÑO-CORDOBA'>NARIÑO-CORDOBA</option>
    <option value='NARIÑO-CUASPUD'>NARIÑO-CUASPUD</option>
    <option value='NARIÑO-CUMBAL'>NARIÑO-CUMBAL</option>
    <option value='NARIÑO-CUMBITARA'>NARIÑO-CUMBITARA</option>
    <option value='NARIÑO-CHACHAGsI'>NARIÑO-CHACHAGsI</option>
    <option value='NARIÑO-EL CHARCO'>NARIÑO-EL CHARCO</option>
    <option value='NARIÑO-EL PEÑOL'>NARIÑO-EL PEÑOL</option>
    <option value='NARIÑO-EL ROSARIO'>NARIÑO-EL ROSARIO</option>
    <option value='NARIÑO-EL TABLON DE GOMEZ'>NARIÑO-EL TABLON DE GOMEZ</option>
    <option value='NARIÑO-EL TAMBO'>NARIÑO-EL TAMBO</option>
    <option value='NARIÑO-FUNES'>NARIÑO-FUNES</option>
    <option value='NARIÑO-GUACHUCAL'>NARIÑO-GUACHUCAL</option>
    <option value='NARIÑO-GUAITARILLA'>NARIÑO-GUAITARILLA</option>
    <option value='NARIÑO-GUALMATAN'>NARIÑO-GUALMATAN</option>
    <option value='NARIÑO-ILES'>NARIÑO-ILES</option>
    <option value='NARIÑO-IMUES'>NARIÑO-IMUES</option>
    <option value='NARIÑO-IPIALES'>NARIÑO-IPIALES</option>
    <option value='NARIÑO-LA CRUZ'>NARIÑO-LA CRUZ</option>
    <option value='NARIÑO-LA FLORIDA'>NARIÑO-LA FLORIDA</option>
    <option value='NARIÑO-LA LLANADA'>NARIÑO-LA LLANADA</option>
    <option value='NARIÑO-LA TOLA'>NARIÑO-LA TOLA</option>
    <option value='NARIÑO-LA UNION'>NARIÑO-LA UNION</option>
    <option value='NARIÑO-LEIVA'>NARIÑO-LEIVA</option>
    <option value='NARIÑO-LINARES'>NARIÑO-LINARES</option>
    <option value='NARIÑO-LOS ANDES'>NARIÑO-LOS ANDES</option>
    <option value='NARIÑO-MAGsI'>NARIÑO-MAGsI</option>
    <option value='NARIÑO-MALLAMA'>NARIÑO-MALLAMA</option>
    <option value='NARIÑO-MOSQUERA'>NARIÑO-MOSQUERA</option>
    <option value='NARIÑO-NARIÑO'>NARIÑO-NARIÑO</option>
    <option value='NARIÑO-OLAYA HERRERA'>NARIÑO-OLAYA HERRERA</option>
    <option value='NARIÑO-OSPINA'>NARIÑO-OSPINA</option>
    <option value='NARIÑO-FRANCISCO PIZARRO'>NARIÑO-FRANCISCO PIZARRO</option>
    <option value='NARIÑO-POLICARPA'>NARIÑO-POLICARPA</option>
    <option value='NARIÑO-POTOSI'>NARIÑO-POTOSI</option>
    <option value='NARIÑO-PROVIDENCIA'>NARIÑO-PROVIDENCIA</option>
    <option value='NARIÑO-PUERRES'>NARIÑO-PUERRES</option>
    <option value='NARIÑO-PUPIALES'>NARIÑO-PUPIALES</option>
    <option value='NARIÑO-RICAURTE'>NARIÑO-RICAURTE</option>
    <option value='NARIÑO-ROBERTO PAYAN'>NARIÑO-ROBERTO PAYAN</option>
    <option value='NARIÑO-SAMANIEGO'>NARIÑO-SAMANIEGO</option>
    <option value='NARIÑO-SANDONA'>NARIÑO-SANDONA</option>
    <option value='NARIÑO-SAN BERNARDO'>NARIÑO-SAN BERNARDO</option>
    <option value='NARIÑO-SAN LORENZO'>NARIÑO-SAN LORENZO</option>
    <option value='NARIÑO-SAN PABLO'>NARIÑO-SAN PABLO</option>
    <option value='NARIÑO-SAN PEDRO DE CARTAGO'>NARIÑO-SAN PEDRO DE CARTAGO</option>
    <option value='NARIÑO-SANTA BARBARA'>NARIÑO-SANTA BARBARA</option>
    <option value='NARIÑO-SANTACRUZ'>NARIÑO-SANTACRUZ</option>
    <option value='NARIÑO-SAPUYES'>NARIÑO-SAPUYES</option>
    <option value='NARIÑO-TAMINANGO'>NARIÑO-TAMINANGO</option>
    <option value='NARIÑO-TANGUA'>NARIÑO-TANGUA</option>
    <option value='NARIÑO-SAN ANDRES DE TUMACO'>NARIÑO-SAN ANDRES DE TUMACO</option>
    <option value='NARIÑO-TUQUERRES'>NARIÑO-TUQUERRES</option>
    <option value='NARIÑO-YACUANQUER'>NARIÑO-YACUANQUER</option>
    <option value='NORTE DE SANTANDER-CUCUTA'>NORTE DE SANTANDER-CUCUTA</option>
    <option value='NORTE DE SANTANDER-ABREGO'>NORTE DE SANTANDER-ABREGO</option>
    <option value='NORTE DE SANTANDER-ARBOLEDAS'>NORTE DE SANTANDER-ARBOLEDAS</option>
    <option value='NORTE DE SANTANDER-BOCHALEMA'>NORTE DE SANTANDER-BOCHALEMA</option>
    <option value='NORTE DE SANTANDER-BUCARASICA'>NORTE DE SANTANDER-BUCARASICA</option>
    <option value='NORTE DE SANTANDER-CACOTA'>NORTE DE SANTANDER-CACOTA</option>
    <option value='NORTE DE SANTANDER-CACHIRA'>NORTE DE SANTANDER-CACHIRA</option>
    <option value='NORTE DE SANTANDER-CHINACOTA'>NORTE DE SANTANDER-CHINACOTA</option>
    <option value='NORTE DE SANTANDER-CHITAGA'>NORTE DE SANTANDER-CHITAGA</option>
    <option value='NORTE DE SANTANDER-CONVENCION'>NORTE DE SANTANDER-CONVENCION</option>
    <option value='NORTE DE SANTANDER-CUCUTILLA'>NORTE DE SANTANDER-CUCUTILLA</option>
    <option value='NORTE DE SANTANDER-DURANIA'>NORTE DE SANTANDER-DURANIA</option>
    <option value='NORTE DE SANTANDER-EL CARMEN'>NORTE DE SANTANDER-EL CARMEN</option>
    <option value='NORTE DE SANTANDER-EL TARRA'>NORTE DE SANTANDER-EL TARRA</option>
    <option value='NORTE DE SANTANDER-EL ZULIA'>NORTE DE SANTANDER-EL ZULIA</option>
    <option value='NORTE DE SANTANDER-GRAMALOTE'>NORTE DE SANTANDER-GRAMALOTE</option>
    <option value='NORTE DE SANTANDER-HACARI'>NORTE DE SANTANDER-HACARI</option>
    <option value='NORTE DE SANTANDER-HERRAN'>NORTE DE SANTANDER-HERRAN</option>
    <option value='NORTE DE SANTANDER-LABATECA'>NORTE DE SANTANDER-LABATECA</option>
    <option value='NORTE DE SANTANDER-LA ESPERANZA'>NORTE DE SANTANDER-LA ESPERANZA</option>
    <option value='NORTE DE SANTANDER-LA PLAYA'>NORTE DE SANTANDER-LA PLAYA</option>
    <option value='NORTE DE SANTANDER-LOS PATIOS'>NORTE DE SANTANDER-LOS PATIOS</option>
    <option value='NORTE DE SANTANDER-LOURDES'>NORTE DE SANTANDER-LOURDES</option>
    <option value='NORTE DE SANTANDER-MUTISCUA'>NORTE DE SANTANDER-MUTISCUA</option>
    <option value='NORTE DE SANTANDER-OCAÑA'>NORTE DE SANTANDER-OCAÑA</option>
    <option value='NORTE DE SANTANDER-PAMPLONA'>NORTE DE SANTANDER-PAMPLONA</option>
    <option value='NORTE DE SANTANDER-PAMPLONITA'>NORTE DE SANTANDER-PAMPLONITA</option>
    <option value='NORTE DE SANTANDER-PUERTO SANTANDER'>NORTE DE SANTANDER-PUERTO SANTANDER</option>
    <option value='NORTE DE SANTANDER-RAGONVALIA'>NORTE DE SANTANDER-RAGONVALIA</option>
    <option value='NORTE DE SANTANDER-SALAZAR'>NORTE DE SANTANDER-SALAZAR</option>
    <option value='NORTE DE SANTANDER-SAN CALIXTO'>NORTE DE SANTANDER-SAN CALIXTO</option>
    <option value='NORTE DE SANTANDER-SAN CAYETANO'>NORTE DE SANTANDER-SAN CAYETANO</option>
    <option value='NORTE DE SANTANDER-SANTIAGO'>NORTE DE SANTANDER-SANTIAGO</option>
    <option value='NORTE DE SANTANDER-SARDINATA'>NORTE DE SANTANDER-SARDINATA</option>
    <option value='NORTE DE SANTANDER-SILOS'>NORTE DE SANTANDER-SILOS</option>
    <option value='NORTE DE SANTANDER-TEORAMA'>NORTE DE SANTANDER-TEORAMA</option>
    <option value='NORTE DE SANTANDER-TIBU'>NORTE DE SANTANDER-TIBU</option>
    <option value='NORTE DE SANTANDER-TOLEDO'>NORTE DE SANTANDER-TOLEDO</option>
    <option value='NORTE DE SANTANDER-VILLA CARO'>NORTE DE SANTANDER-VILLA CARO</option>
    <option value='NORTE DE SANTANDER-VILLA DEL ROSARIO'>NORTE DE SANTANDER-VILLA DEL ROSARIO</option>
    <option value='QUINDIO-ARMENIA'>QUINDIO-ARMENIA</option>
    <option value='QUINDIO-BUENAVISTA'>QUINDIO-BUENAVISTA</option>
    <option value='QUINDIO-CALARCA'>QUINDIO-CALARCA</option>
    <option value='QUINDIO-CIRCASIA'>QUINDIO-CIRCASIA</option>
    <option value='QUINDIO-CORDOBA'>QUINDIO-CORDOBA</option>
    <option value='QUINDIO-FILANDIA'>QUINDIO-FILANDIA</option>
    <option value='QUINDIO-GENOVA'>QUINDIO-GENOVA</option>
    <option value='QUINDIO-LA TEBAIDA'>QUINDIO-LA TEBAIDA</option>
    <option value='QUINDIO-MONTENEGRO'>QUINDIO-MONTENEGRO</option>
    <option value='QUINDIO-PIJAO'>QUINDIO-PIJAO</option>
    <option value='QUINDIO-QUIMBAYA'>QUINDIO-QUIMBAYA</option>
    <option value='QUINDIO-SALENTO'>QUINDIO-SALENTO</option>
    <option value='RISARALDA-PEREIRA'>RISARALDA-PEREIRA</option>
    <option value='RISARALDA-APIA'>RISARALDA-APIA</option>
    <option value='RISARALDA-BALBOA'>RISARALDA-BALBOA</option>
    <option value='RISARALDA-BELEN DE UMBRIA'>RISARALDA-BELEN DE UMBRIA</option>
    <option value='RISARALDA-DOSQUEBRADAS'>RISARALDA-DOSQUEBRADAS</option>
    <option value='RISARALDA-GUATICA'>RISARALDA-GUATICA</option>
    <option value='RISARALDA-LA CELIA'>RISARALDA-LA CELIA</option>
    <option value='RISARALDA-LA VIRGINIA'>RISARALDA-LA VIRGINIA</option>
    <option value='RISARALDA-MARSELLA'>RISARALDA-MARSELLA</option>
    <option value='RISARALDA-MISTRATO'>RISARALDA-MISTRATO</option>
    <option value='RISARALDA-PUEBLO RICO'>RISARALDA-PUEBLO RICO</option>
    <option value='RISARALDA-QUINCHIA'>RISARALDA-QUINCHIA</option>
    <option value='RISARALDA-SANTA ROSA DE CABAL'>RISARALDA-SANTA ROSA DE CABAL</option>
    <option value='RISARALDA-SANTUARIO'>RISARALDA-SANTUARIO</option>
    <option value='SANTANDER-BUCARAMANGA'>SANTANDER-BUCARAMANGA</option>
    <option value='SANTANDER-AGUADA'>SANTANDER-AGUADA</option>
    <option value='SANTANDER-ALBANIA'>SANTANDER-ALBANIA</option>
    <option value='SANTANDER-ARATOCA'>SANTANDER-ARATOCA</option>
    <option value='SANTANDER-BARBOSA'>SANTANDER-BARBOSA</option>
    <option value='SANTANDER-BARICHARA'>SANTANDER-BARICHARA</option>
    <option value='SANTANDER-BARRANCABERMEJA'>SANTANDER-BARRANCABERMEJA</option>
    <option value='SANTANDER-BETULIA'>SANTANDER-BETULIA</option>
    <option value='SANTANDER-BOLIVAR'>SANTANDER-BOLIVAR</option>
    <option value='SANTANDER-CABRERA'>SANTANDER-CABRERA</option>
    <option value='SANTANDER-CALIFORNIA'>SANTANDER-CALIFORNIA</option>
    <option value='SANTANDER-CAPITANEJO'>SANTANDER-CAPITANEJO</option>
    <option value='SANTANDER-CARCASI'>SANTANDER-CARCASI</option>
    <option value='SANTANDER-CEPITA'>SANTANDER-CEPITA</option>
    <option value='SANTANDER-CERRITO'>SANTANDER-CERRITO</option>
    <option value='SANTANDER-CHARALA'>SANTANDER-CHARALA</option>
    <option value='SANTANDER-CHARTA'>SANTANDER-CHARTA</option>
    <option value='SANTANDER-CHIMA'>SANTANDER-CHIMA</option>
    <option value='SANTANDER-CHIPATA'>SANTANDER-CHIPATA</option>
    <option value='SANTANDER-CIMITARRA'>SANTANDER-CIMITARRA</option>
    <option value='SANTANDER-CONCEPCION'>SANTANDER-CONCEPCION</option>
    <option value='SANTANDER-CONFINES'>SANTANDER-CONFINES</option>
    <option value='SANTANDER-CONTRATACION'>SANTANDER-CONTRATACION</option>
    <option value='SANTANDER-COROMORO'>SANTANDER-COROMORO</option>
    <option value='SANTANDER-CURITI'>SANTANDER-CURITI</option>
    <option value='SANTANDER-EL CARMEN DE CHUCURI'>SANTANDER-EL CARMEN DE CHUCURI</option>
    <option value='SANTANDER-EL GUACAMAYO'>SANTANDER-EL GUACAMAYO</option>
    <option value='SANTANDER-EL PEÑON'>SANTANDER-EL PEÑON</option>
    <option value='SANTANDER-EL PLAYON'>SANTANDER-EL PLAYON</option>
    <option value='SANTANDER-ENCINO'>SANTANDER-ENCINO</option>
    <option value='SANTANDER-ENCISO'>SANTANDER-ENCISO</option>
    <option value='SANTANDER-FLORIAN'>SANTANDER-FLORIAN</option>
    <option value='SANTANDER-FLORIDABLANCA'>SANTANDER-FLORIDABLANCA</option>
    <option value='SANTANDER-GALAN'>SANTANDER-GALAN</option>
    <option value='SANTANDER-GAMBITA'>SANTANDER-GAMBITA</option>
    <option value='SANTANDER-GIRON'>SANTANDER-GIRON</option>
    <option value='SANTANDER-GUACA'>SANTANDER-GUACA</option>
    <option value='SANTANDER-GUADALUPE'>SANTANDER-GUADALUPE</option>
    <option value='SANTANDER-GUAPOTA'>SANTANDER-GUAPOTA</option>
    <option value='SANTANDER-GUAVATA'>SANTANDER-GUAVATA</option>
    <option value='SANTANDER-GsEPSA'>SANTANDER-GsEPSA</option>
    <option value='SANTANDER-HATO'>SANTANDER-HATO</option>
    <option value='SANTANDER-JESUS MARIA'>SANTANDER-JESUS MARIA</option>
    <option value='SANTANDER-JORDAN'>SANTANDER-JORDAN</option>
    <option value='SANTANDER-LA BELLEZA'>SANTANDER-LA BELLEZA</option>
    <option value='SANTANDER-LANDAZURI'>SANTANDER-LANDAZURI</option>
    <option value='SANTANDER-LA PAZ'>SANTANDER-LA PAZ</option>
    <option value='SANTANDER-LEBRIJA'>SANTANDER-LEBRIJA</option>
    <option value='SANTANDER-LOS SANTOS'>SANTANDER-LOS SANTOS</option>
    <option value='SANTANDER-MACARAVITA'>SANTANDER-MACARAVITA</option>
    <option value='SANTANDER-MALAGA'>SANTANDER-MALAGA</option>
    <option value='SANTANDER-MATANZA'>SANTANDER-MATANZA</option>
    <option value='SANTANDER-MOGOTES'>SANTANDER-MOGOTES</option>
    <option value='SANTANDER-MOLAGAVITA'>SANTANDER-MOLAGAVITA</option>
    <option value='SANTANDER-OCAMONTE'>SANTANDER-OCAMONTE</option>
    <option value='SANTANDER-OIBA'>SANTANDER-OIBA</option>
    <option value='SANTANDER-ONZAGA'>SANTANDER-ONZAGA</option>
    <option value='SANTANDER-PALMAR'>SANTANDER-PALMAR</option>
    <option value='SANTANDER-PALMAS DEL SOCORRO'>SANTANDER-PALMAS DEL SOCORRO</option>
    <option value='SANTANDER-PARAMO'>SANTANDER-PARAMO</option>
    <option value='SANTANDER-PIEDECUESTA'>SANTANDER-PIEDECUESTA</option>
    <option value='SANTANDER-PINCHOTE'>SANTANDER-PINCHOTE</option>
    <option value='SANTANDER-PUENTE NACIONAL'>SANTANDER-PUENTE NACIONAL</option>
    <option value='SANTANDER-PUERTO PARRA'>SANTANDER-PUERTO PARRA</option>
    <option value='SANTANDER-PUERTO WILCHES'>SANTANDER-PUERTO WILCHES</option>
    <option value='SANTANDER-RIONEGRO'>SANTANDER-RIONEGRO</option>
    <option value='SANTANDER-SABANA DE TORRES'>SANTANDER-SABANA DE TORRES</option>
    <option value='SANTANDER-SAN ANDRES'>SANTANDER-SAN ANDRES</option>
    <option value='SANTANDER-SAN BENITO'>SANTANDER-SAN BENITO</option>
    <option value='SANTANDER-SAN GIL'>SANTANDER-SAN GIL</option>
    <option value='SANTANDER-SAN JOAQUIN'>SANTANDER-SAN JOAQUIN</option>
    <option value='SANTANDER-SAN JOSE DE MIRANDA'>SANTANDER-SAN JOSE DE MIRANDA</option>
    <option value='SANTANDER-SAN MIGUEL'>SANTANDER-SAN MIGUEL</option>
    <option value='SANTANDER-SAN VICENTE DE CHUCURI'>SANTANDER-SAN VICENTE DE CHUCURI</option>
    <option value='SANTANDER-SANTA BARBARA'>SANTANDER-SANTA BARBARA</option>
    <option value='SANTANDER-SANTA HELENA DEL OPON'>SANTANDER-SANTA HELENA DEL OPON</option>
    <option value='SANTANDER-SIMACOTA'>SANTANDER-SIMACOTA</option>
    <option value='SANTANDER-SOCORRO'>SANTANDER-SOCORRO</option>
    <option value='SANTANDER-SUAITA'>SANTANDER-SUAITA</option>
    <option value='SANTANDER-SUCRE'>SANTANDER-SUCRE</option>
    <option value='SANTANDER-SURATA'>SANTANDER-SURATA</option>
    <option value='SANTANDER-TONA'>SANTANDER-TONA</option>
    <option value='SANTANDER-VALLE DE SAN JOSE'>SANTANDER-VALLE DE SAN JOSE</option>
    <option value='SANTANDER-VELEZ'>SANTANDER-VELEZ</option>
    <option value='SANTANDER-VETAS'>SANTANDER-VETAS</option>
    <option value='SANTANDER-VILLANUEVA'>SANTANDER-VILLANUEVA</option>
    <option value='SANTANDER-ZAPATOCA'>SANTANDER-ZAPATOCA</option>
    <option value='SUCRE-SINCELEJO'>SUCRE-SINCELEJO</option>
    <option value='SUCRE-BUENAVISTA'>SUCRE-BUENAVISTA</option>
    <option value='SUCRE-CAIMITO'>SUCRE-CAIMITO</option>
    <option value='SUCRE-COLOSO'>SUCRE-COLOSO</option>
    <option value='SUCRE-COROZAL'>SUCRE-COROZAL</option>
    <option value='SUCRE-COVEÑAS'>SUCRE-COVEÑAS</option>
    <option value='SUCRE-CHALAN'>SUCRE-CHALAN</option>
    <option value='SUCRE-EL ROBLE'>SUCRE-EL ROBLE</option>
    <option value='SUCRE-GALERAS'>SUCRE-GALERAS</option>
    <option value='SUCRE-GUARANDA'>SUCRE-GUARANDA</option>
    <option value='SUCRE-LA UNION'>SUCRE-LA UNION</option>
    <option value='SUCRE-LOS PALMITOS'>SUCRE-LOS PALMITOS</option>
    <option value='SUCRE-MAJAGUAL'>SUCRE-MAJAGUAL</option>
    <option value='SUCRE-MORROA'>SUCRE-MORROA</option>
    <option value='SUCRE-OVEJAS'>SUCRE-OVEJAS</option>
    <option value='SUCRE-PALMITO'>SUCRE-PALMITO</option>
    <option value='SUCRE-SAMPUES'>SUCRE-SAMPUES</option>
    <option value='SUCRE-SAN BENITO ABAD'>SUCRE-SAN BENITO ABAD</option>
    <option value='SUCRE-SAN JUAN DE BETULIA'>SUCRE-SAN JUAN DE BETULIA</option>
    <option value='SUCRE-SAN MARCOS'>SUCRE-SAN MARCOS</option>
    <option value='SUCRE-SAN ONOFRE'>SUCRE-SAN ONOFRE</option>
    <option value='SUCRE-SAN PEDRO'>SUCRE-SAN PEDRO</option>
    <option value='SUCRE-SAN LUIS DE SINCE'>SUCRE-SAN LUIS DE SINCE</option>
    <option value='SUCRE-SUCRE'>SUCRE-SUCRE</option>
    <option value='SUCRE-SANTIAGO DE TOLU'>SUCRE-SANTIAGO DE TOLU</option>
    <option value='SUCRE-TOLU VIEJO'>SUCRE-TOLU VIEJO</option>
    <option value='TOLIMA-IBAGUE'>TOLIMA-IBAGUE</option>
    <option value='TOLIMA-ALPUJARRA'>TOLIMA-ALPUJARRA</option>
    <option value='TOLIMA-ALVARADO'>TOLIMA-ALVARADO</option>
    <option value='TOLIMA-AMBALEMA'>TOLIMA-AMBALEMA</option>
    <option value='TOLIMA-ANZOATEGUI'>TOLIMA-ANZOATEGUI</option>
    <option value='TOLIMA-ARMERO'>TOLIMA-ARMERO</option>
    <option value='TOLIMA-ATACO'>TOLIMA-ATACO</option>
    <option value='TOLIMA-CAJAMARCA'>TOLIMA-CAJAMARCA</option>
    <option value='TOLIMA-CARMEN DE APICALA'>TOLIMA-CARMEN DE APICALA</option>
    <option value='TOLIMA-CASABIANCA'>TOLIMA-CASABIANCA</option>
    <option value='TOLIMA-CHAPARRAL'>TOLIMA-CHAPARRAL</option>
    <option value='TOLIMA-COELLO'>TOLIMA-COELLO</option>
    <option value='TOLIMA-COYAIMA'>TOLIMA-COYAIMA</option>
    <option value='TOLIMA-CUNDAY'>TOLIMA-CUNDAY</option>
    <option value='TOLIMA-DOLORES'>TOLIMA-DOLORES</option>
    <option value='TOLIMA-ESPINAL'>TOLIMA-ESPINAL</option>
    <option value='TOLIMA-FALAN'>TOLIMA-FALAN</option>
    <option value='TOLIMA-FLANDES'>TOLIMA-FLANDES</option>
    <option value='TOLIMA-FRESNO'>TOLIMA-FRESNO</option>
    <option value='TOLIMA-GUAMO'>TOLIMA-GUAMO</option>
    <option value='TOLIMA-HERVEO'>TOLIMA-HERVEO</option>
    <option value='TOLIMA-HONDA'>TOLIMA-HONDA</option>
    <option value='TOLIMA-ICONONZO'>TOLIMA-ICONONZO</option>
    <option value='TOLIMA-LERIDA'>TOLIMA-LERIDA</option>
    <option value='TOLIMA-LIBANO'>TOLIMA-LIBANO</option>
    <option value='TOLIMA-MARIQUITA'>TOLIMA-MARIQUITA</option>
    <option value='TOLIMA-MELGAR'>TOLIMA-MELGAR</option>
    <option value='TOLIMA-MURILLO'>TOLIMA-MURILLO</option>
    <option value='TOLIMA-NATAGAIMA'>TOLIMA-NATAGAIMA</option>
    <option value='TOLIMA-ORTEGA'>TOLIMA-ORTEGA</option>
    <option value='TOLIMA-PALOCABILDO'>TOLIMA-PALOCABILDO</option>
    <option value='TOLIMA-PIEDRAS'>TOLIMA-PIEDRAS</option>
    <option value='TOLIMA-PLANADAS'>TOLIMA-PLANADAS</option>
    <option value='TOLIMA-PRADO'>TOLIMA-PRADO</option>
    <option value='TOLIMA-PURIFICACION'>TOLIMA-PURIFICACION</option>
    <option value='TOLIMA-RIOBLANCO'>TOLIMA-RIOBLANCO</option>
    <option value='TOLIMA-RONCESVALLES'>TOLIMA-RONCESVALLES</option>
    <option value='TOLIMA-ROVIRA'>TOLIMA-ROVIRA</option>
    <option value='TOLIMA-SALDAÑA'>TOLIMA-SALDAÑA</option>
    <option value='TOLIMA-SAN ANTONIO'>TOLIMA-SAN ANTONIO</option>
    <option value='TOLIMA-SAN LUIS'>TOLIMA-SAN LUIS</option>
    <option value='TOLIMA-SANTA ISABEL'>TOLIMA-SANTA ISABEL</option>
    <option value='TOLIMA-SUAREZ'>TOLIMA-SUAREZ</option>
    <option value='TOLIMA-VALLE DE SAN JUAN'>TOLIMA-VALLE DE SAN JUAN</option>
    <option value='TOLIMA-VENADILLO'>TOLIMA-VENADILLO</option>
    <option value='TOLIMA-VILLAHERMOSA'>TOLIMA-VILLAHERMOSA</option>
    <option value='TOLIMA-VILLARRICA'>TOLIMA-VILLARRICA</option>
    <option value='VALLE DEL CAUCA-CALI'>VALLE DEL CAUCA-CALI</option>
    <option value='VALLE DEL CAUCA-ALCALA'>VALLE DEL CAUCA-ALCALA</option>
    <option value='VALLE DEL CAUCA-ANDALUCIA'>VALLE DEL CAUCA-ANDALUCIA</option>
    <option value='VALLE DEL CAUCA-ANSERMANUEVO'>VALLE DEL CAUCA-ANSERMANUEVO</option>
    <option value='VALLE DEL CAUCA-ARGELIA'>VALLE DEL CAUCA-ARGELIA</option>
    <option value='VALLE DEL CAUCA-BOLIVAR'>VALLE DEL CAUCA-BOLIVAR</option>
    <option value='VALLE DEL CAUCA-BUENAVENTURA'>VALLE DEL CAUCA-BUENAVENTURA</option>
    <option value='VALLE DEL CAUCA-GUADALAJARA DE BUGA'>VALLE DEL CAUCA-GUADALAJARA DE BUGA</option>
    <option value='VALLE DEL CAUCA-BUGALAGRANDE'>VALLE DEL CAUCA-BUGALAGRANDE</option>
    <option value='VALLE DEL CAUCA-CAICEDONIA'>VALLE DEL CAUCA-CAICEDONIA</option>
    <option value='VALLE DEL CAUCA-CALIMA'>VALLE DEL CAUCA-CALIMA</option>
    <option value='VALLE DEL CAUCA-CANDELARIA'>VALLE DEL CAUCA-CANDELARIA</option>
    <option value='VALLE DEL CAUCA-CARTAGO'>VALLE DEL CAUCA-CARTAGO</option>
    <option value='VALLE DEL CAUCA-DAGUA'>VALLE DEL CAUCA-DAGUA</option>
    <option value='VALLE DEL CAUCA-EL AGUILA'>VALLE DEL CAUCA-EL AGUILA</option>
    <option value='VALLE DEL CAUCA-EL CAIRO'>VALLE DEL CAUCA-EL CAIRO</option>
    <option value='VALLE DEL CAUCA-EL CERRITO'>VALLE DEL CAUCA-EL CERRITO</option>
    <option value='VALLE DEL CAUCA-EL DOVIO'>VALLE DEL CAUCA-EL DOVIO</option>
    <option value='VALLE DEL CAUCA-FLORIDA'>VALLE DEL CAUCA-FLORIDA</option>
    <option value='VALLE DEL CAUCA-GINEBRA'>VALLE DEL CAUCA-GINEBRA</option>
    <option value='VALLE DEL CAUCA-GUACARI'>VALLE DEL CAUCA-GUACARI</option>
    <option value='VALLE DEL CAUCA-JAMUNDI'>VALLE DEL CAUCA-JAMUNDI</option>
    <option value='VALLE DEL CAUCA-LA CUMBRE'>VALLE DEL CAUCA-LA CUMBRE</option>
    <option value='VALLE DEL CAUCA-LA UNION'>VALLE DEL CAUCA-LA UNION</option>
    <option value='VALLE DEL CAUCA-LA VICTORIA'>VALLE DEL CAUCA-LA VICTORIA</option>
    <option value='VALLE DEL CAUCA-OBANDO'>VALLE DEL CAUCA-OBANDO</option>
    <option value='VALLE DEL CAUCA-PALMIRA'>VALLE DEL CAUCA-PALMIRA</option>
    <option value='VALLE DEL CAUCA-PRADERA'>VALLE DEL CAUCA-PRADERA</option>
    <option value='VALLE DEL CAUCA-RESTREPO'>VALLE DEL CAUCA-RESTREPO</option>
    <option value='VALLE DEL CAUCA-RIOFRIO'>VALLE DEL CAUCA-RIOFRIO</option>
    <option value='VALLE DEL CAUCA-ROLDANILLO'>VALLE DEL CAUCA-ROLDANILLO</option>
    <option value='VALLE DEL CAUCA-SAN PEDRO'>VALLE DEL CAUCA-SAN PEDRO</option>
    <option value='VALLE DEL CAUCA-SEVILLA'>VALLE DEL CAUCA-SEVILLA</option>
    <option value='VALLE DEL CAUCA-TORO'>VALLE DEL CAUCA-TORO</option>
    <option value='VALLE DEL CAUCA-TRUJILLO'>VALLE DEL CAUCA-TRUJILLO</option>
    <option value='VALLE DEL CAUCA-TULUA'>VALLE DEL CAUCA-TULUA</option>
    <option value='VALLE DEL CAUCA-ULLOA'>VALLE DEL CAUCA-ULLOA</option>
    <option value='VALLE DEL CAUCA-VERSALLES'>VALLE DEL CAUCA-VERSALLES</option>
    <option value='VALLE DEL CAUCA-VIJES'>VALLE DEL CAUCA-VIJES</option>
    <option value='VALLE DEL CAUCA-YOTOCO'>VALLE DEL CAUCA-YOTOCO</option>
    <option value='VALLE DEL CAUCA-YUMBO'>VALLE DEL CAUCA-YUMBO</option>
    <option value='VALLE DEL CAUCA-ZARZAL'>VALLE DEL CAUCA-ZARZAL</option>
    <option value='ARAUCA-ARAUCA'>ARAUCA-ARAUCA</option>
    <option value='ARAUCA-ARAUQUITA'>ARAUCA-ARAUQUITA</option>
    <option value='ARAUCA-CRAVO NORTE'>ARAUCA-CRAVO NORTE</option>
    <option value='ARAUCA-FORTUL'>ARAUCA-FORTUL</option>
    <option value='ARAUCA-PUERTO RONDON'>ARAUCA-PUERTO RONDON</option>
    <option value='ARAUCA-SARAVENA'>ARAUCA-SARAVENA</option>
    <option value='ARAUCA-TAME'>ARAUCA-TAME</option>
    <option value='CASANARE-YOPAL'>CASANARE-YOPAL</option>
    <option value='CASANARE-AGUAZUL'>CASANARE-AGUAZUL</option>
    <option value='CASANARE-CHAMEZA'>CASANARE-CHAMEZA</option>
    <option value='CASANARE-HATO COROZAL'>CASANARE-HATO COROZAL</option>
    <option value='CASANARE-LA SALINA'>CASANARE-LA SALINA</option>
    <option value='CASANARE-MANI'>CASANARE-MANI</option>
    <option value='CASANARE-MONTERREY'>CASANARE-MONTERREY</option>
    <option value='CASANARE-NUNCHIA'>CASANARE-NUNCHIA</option>
    <option value='CASANARE-OROCUE'>CASANARE-OROCUE</option>
    <option value='CASANARE-PAZ DE ARIPORO'>CASANARE-PAZ DE ARIPORO</option>
    <option value='CASANARE-PORE'>CASANARE-PORE</option>
    <option value='CASANARE-RECETOR'>CASANARE-RECETOR</option>
    <option value='CASANARE-SABANALARGA'>CASANARE-SABANALARGA</option>
    <option value='CASANARE-SACAMA'>CASANARE-SACAMA</option>
    <option value='CASANARE-SAN LUIS DE PALENQUE'>CASANARE-SAN LUIS DE PALENQUE</option>
    <option value='CASANARE-TAMARA'>CASANARE-TAMARA</option>
    <option value='CASANARE-TAURAMENA'>CASANARE-TAURAMENA</option>
    <option value='CASANARE-TRINIDAD'>CASANARE-TRINIDAD</option>
    <option value='CASANARE-VILLANUEVA'>CASANARE-VILLANUEVA</option>
    <option value='PUTUMAYO-MOCOA'>PUTUMAYO-MOCOA</option>
    <option value='PUTUMAYO-COLON'>PUTUMAYO-COLON</option>
    <option value='PUTUMAYO-ORITO'>PUTUMAYO-ORITO</option>
    <option value='PUTUMAYO-PUERTO ASIS'>PUTUMAYO-PUERTO ASIS</option>
    <option value='PUTUMAYO-PUERTO CAICEDO'>PUTUMAYO-PUERTO CAICEDO</option>
    <option value='PUTUMAYO-PUERTO GUZMAN'>PUTUMAYO-PUERTO GUZMAN</option>
    <option value='PUTUMAYO-LEGUIZAMO'>PUTUMAYO-LEGUIZAMO</option>
    <option value='PUTUMAYO-SIBUNDOY'>PUTUMAYO-SIBUNDOY</option>
    <option value='PUTUMAYO-SAN FRANCISCO'>PUTUMAYO-SAN FRANCISCO</option>
    <option value='PUTUMAYO-SAN MIGUEL'>PUTUMAYO-SAN MIGUEL</option>
    <option value='PUTUMAYO-SANTIAGO'>PUTUMAYO-SANTIAGO</option>
    <option value='PUTUMAYO-VALLE DEL GUAMUEZ'>PUTUMAYO-VALLE DEL GUAMUEZ</option>
    <option value='PUTUMAYO-VILLAGARZON'>PUTUMAYO-VILLAGARZON</option>
    <option value='SAN ANDRES-SAN ANDRES'>SAN ANDRES-SAN ANDRES</option>
    <option value='SAN ANDRES-PROVIDENCIA'>SAN ANDRES-PROVIDENCIA</option>
    <option value='AMAZONAS-LETICIA'>AMAZONAS-LETICIA</option>
    <option value='AMAZONAS-EL ENCANTO'>AMAZONAS-EL ENCANTO</option>
    <option value='AMAZONAS-LA CHORRERA'>AMAZONAS-LA CHORRERA</option>
    <option value='AMAZONAS-LA PEDRERA'>AMAZONAS-LA PEDRERA</option>
    <option value='AMAZONAS-LA VICTORIA'>AMAZONAS-LA VICTORIA</option>
    <option value='AMAZONAS-MIRITI - PARANA'>AMAZONAS-MIRITI - PARANA</option>
    <option value='AMAZONAS-PUERTO ALEGRIA'>AMAZONAS-PUERTO ALEGRIA</option>
    <option value='AMAZONAS-PUERTO ARICA'>AMAZONAS-PUERTO ARICA</option>
    <option value='AMAZONAS-PUERTO NARIÑO'>AMAZONAS-PUERTO NARIÑO</option>
    <option value='AMAZONAS-PUERTO SANTANDER'>AMAZONAS-PUERTO SANTANDER</option>
    <option value='AMAZONAS-TARAPACA'>AMAZONAS-TARAPACA</option>
    <option value='GUAINIA-INIRIDA'>GUAINIA-INIRIDA</option>
    <option value='GUAINIA-BARRANCO MINAS'>GUAINIA-BARRANCO MINAS</option>
    <option value='GUAINIA-MAPIRIPANA'>GUAINIA-MAPIRIPANA</option>
    <option value='GUAINIA-SAN FELIPE'>GUAINIA-SAN FELIPE</option>
    <option value='GUAINIA-PUERTO COLOMBIA'>GUAINIA-PUERTO COLOMBIA</option>
    <option value='GUAINIA-LA GUADALUPE'>GUAINIA-LA GUADALUPE</option>
    <option value='GUAINIA-CACAHUAL'>GUAINIA-CACAHUAL</option>
    <option value='GUAINIA-PANA PANA'>GUAINIA-PANA PANA</option>
    <option value='GUAINIA-MORICHAL'>GUAINIA-MORICHAL</option>
    <option value='GUAVIARE-SAN JOSE DEL GUAVIARE'>GUAVIARE-SAN JOSE DEL GUAVIARE</option>
    <option value='GUAVIARE-CALAMAR'>GUAVIARE-CALAMAR</option>
    <option value='GUAVIARE-EL RETORNO'>GUAVIARE-EL RETORNO</option>
    <option value='GUAVIARE-MIRAFLORES'>GUAVIARE-MIRAFLORES</option>
    <option value='VAUPES-MITU'>VAUPES-MITU</option>
    <option value='VAUPES-CARURU'>VAUPES-CARURU</option>
    <option value='VAUPES-PACOA'>VAUPES-PACOA</option>
    <option value='VAUPES-TARAIRA'>VAUPES-TARAIRA</option>
    <option value='VAUPES-PAPUNAUA'>VAUPES-PAPUNAUA</option>
    <option value='VAUPES-YAVARATE'>VAUPES-YAVARATE</option>
    <option value='VICHADA-PUERTO CARREÑO'>VICHADA-PUERTO CARREÑO</option>
    <option value='VICHADA-LA PRIMAVERA'>VICHADA-LA PRIMAVERA</option>
    <option value='VICHADA-SANTA ROSALIA'>VICHADA-SANTA ROSALIA</option>
    <option value='VICHADA-CUMARIBO'>VICHADA-CUMARIBO</option>